Repository golangci/golangci-lint, pull requests merged in 2019-09, with the labels that each got.

#621 linters: add Godox linter support
  .golangci.example.yml
  .golangci.yml
  README.md
  go.mod
  go.sum
  pkg/config/config.go
  pkg/golinters/godox.go
  pkg/lint/lintersdb/manager.go
  test/testdata/godox.go
  vendor/github.com/matoous/godox/.gitignore
  vendor/github.com/matoous/godox/.golangci.yml
  vendor/github.com/matoous/godox/.revive.toml
  vendor/github.com/matoous/godox/LICENSE
  vendor/github.com/matoous/godox/README.md
  vendor/github.com/matoous/godox/go.mod
  vendor/github.com/matoous/godox/go.sum
  vendor/github.com/matoous/godox/godox.go
  vendor/modules.txt
Labels: question

#747 Fix broken dominikh/go-tools URLs
  README.md
  pkg/lint/lintersdb/manager.go
Labels: docs

#751 Update to latest timakin/bodyclose
  go.mod
  go.sum
  vendor/modules.txt
Labels: bug

#759 govet: add more analyzers
  pkg/golinters/govet.go
  vendor/golang.org/x/tools/go/analysis/passes/deepequalerrors/deepequalerrors.go
  vendor/golang.org/x/tools/go/analysis/passes/findcall/findcall.go
  vendor/golang.org/x/tools/go/analysis/passes/nilness/nilness.go
  vendor/golang.org/x/tools/go/analysis/passes/pkgfact/pkgfact.go
  vendor/golang.org/x/tools/go/analysis/passes/sortslice/analyzer.go
  vendor/modules.txt
Labels: new linter

#757 add cyclone to the list of great projects
  README.md
  README.tmpl.md
Labels: docs

#766 Fix incorrect description
  README.md
  pkg/golinters/gochecknoglobals.go
Labels: docs
