Repository golangci/golangci-lint, pull requests merged in 2019-10, with the labels that each got.

#764 reduce 1.5x memory usage on large repos on repeated runs
  pkg/commands/run.go
  pkg/golinters/goanalysis/linter.go
  pkg/golinters/goanalysis/runner.go
  pkg/lint/astcache/astcache.go
  pkg/lint/linter/context.go
  pkg/lint/load.go
  pkg/lint/runner.go
  pkg/logutils/stderr_log.go
  pkg/packages/util.go
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/autogenerated_exclude_test.go
  pkg/result/processors/filename_unadjuster.go
  pkg/result/processors/nolint.go
  pkg/result/processors/nolint_test.go
  pkg/result/processors/testdata/autogen_exclude.go
Labels: memory

#769 Group imports by package
  internal/errorutil/errors.go
  internal/pkgcache/pkgcache.go
  pkg/commands/config.go
  pkg/commands/executor.go
  pkg/commands/run.go
  pkg/config/reader.go
  pkg/fsutils/filecache.go
  pkg/golinters/depguard.go
  pkg/golinters/errcheck.go
  pkg/golinters/funlen.go
  pkg/golinters/goanalysis/runner.go
  pkg/golinters/gochecknoglobals.go
  pkg/golinters/gocritic.go
  pkg/golinters/godox.go
  pkg/golinters/gosec.go
  pkg/golinters/govet.go
  pkg/golinters/govet_test.go
  pkg/golinters/ineffassign.go
  pkg/golinters/interfacer.go
  pkg/golinters/megacheck.go
  pkg/golinters/unused.go
  pkg/golinters/whitespace.go
  pkg/lint/lintersdb/enabled_set.go
  pkg/lint/lintersdb/manager.go
  pkg/lint/load.go
  pkg/lint/runner.go
  pkg/result/issue.go
  pkg/result/processors/exclude_rules.go
  pkg/result/processors/exclude_rules_test.go
  pkg/result/processors/fixer.go
  pkg/result/processors/max_same_issues.go
  pkg/result/processors/processor.go
  pkg/result/processors/uniq_by_line_test.go
  test/bench/bench_test.go
  test/data.go
  test/linters_test.go
  test/run_test.go
Labels: cleanup

#767 Add version command to print golangci-lint version
  pkg/commands/executor.go
  pkg/commands/version.go
Labels: enhancement

#772 Update to latest godownloader/goreleaser versions
  tools/go.mod
  tools/go.sum
Labels: bug, installation

#776 fix misplaced backtick in example config in readme
  .golangci.example.yml
Labels: docs

#777 Regenerate README
  README.md
Labels: docs

#774 Improve the error output from goimports
  pkg/golinters/gofmt_common.go
Labels: enhancement

#778 Enable all gocritic tags
  .golangci.yml
  README.md
Labels: config, enhancement

#779 Cleanup nolint directives
  .golangci.yml
  README.md
  internal/cache/cache.go
  pkg/config/config.go
  pkg/config/config_gocritic.go
  pkg/golinters/goanalysis/runner.go
  pkg/lint/lintersdb/enabled_set.go
  pkg/lint/load.go
  pkg/packages/util.go
  pkg/printers/codeclimate.go
  pkg/result/processors/fixer.go
Labels: cleanup

#787 Add more gocognit tests
  test/testdata/gocognit.go
Labels: enhancement, new linter

#771 Add WSL linter
  README.md
  go.mod
  go.sum
  pkg/golinters/wsl.go
  pkg/lint/lintersdb/manager.go
  test/testdata/wsl.go
  vendor/github.com/bombsimon/wsl/.gitignore
  vendor/github.com/bombsimon/wsl/.travis.yml
  vendor/github.com/bombsimon/wsl/LICENSE
  vendor/github.com/bombsimon/wsl/README.md
  vendor/github.com/bombsimon/wsl/go.mod
  vendor/github.com/bombsimon/wsl/go.sum
  vendor/github.com/bombsimon/wsl/wsl.go
  vendor/gopkg.in/yaml.v2/decode.go
  vendor/gopkg.in/yaml.v2/resolve.go
  vendor/gopkg.in/yaml.v2/scannerc.go
  vendor/modules.txt
Labels: new linter

#784 README: Add SoundCloud to "Trusted By" section
  README.md
  README.tmpl.md
Labels: docs

#788 Reduce cache directory permissions
  internal/cache/cache.go
  internal/cache/cache_test.go
  internal/cache/default.go
Labels: enhancement, security

#789 Update to mattn/go-colorable v0.1.4
  go.mod
  go.sum
  vendor/github.com/mattn/go-colorable/colorable_appengine.go
  vendor/github.com/mattn/go-colorable/colorable_others.go
  vendor/github.com/mattn/go-colorable/colorable_windows.go
  vendor/github.com/mattn/go-colorable/noncolorable.go
  vendor/modules.txt
Labels: dependency, enhancement

#794 Update WSL to v1.2.1
  .golangci.example.yml
  README.md
  go.mod
  go.sum
  pkg/config/config.go
  pkg/golinters/wsl.go
  test/testdata/wsl.go
  vendor/github.com/bombsimon/wsl/README.md
  vendor/github.com/bombsimon/wsl/go.mod
  vendor/github.com/bombsimon/wsl/go.sum
  vendor/github.com/bombsimon/wsl/wsl.go
  vendor/modules.txt
Labels: dependency, false positive

#790 Add ppc64le release
  .goreleaser.yml
Labels: enhancement, installation

#793 Rename deadline option to timeout and mark deadline as deprecated
  .golangci.example.yml
  Makefile
  README.md
  README.tmpl.md
  pkg/commands/run.go
  pkg/config/config.go
  test/run_test.go
Labels: config, docs

#797 Add s390x release
  .goreleaser.yml
Labels: enhancement, installation

#798 Fix docker builds
  .goreleaser.yml
Labels: bug, installation

#801 Update to latest godownloader/goreleaser versions
  tools/go.mod
  tools/go.sum
Labels: dependency

#781 Exposed modules-download-mode as a command line option
  pkg/commands/run.go
Labels: config, enhancement

#811 Update WSL to v1.2.5
  .golangci.example.yml
  README.md
  go.mod
  go.sum
  pkg/config/config.go
  pkg/golinters/wsl.go
  test/linters_test.go
  test/testdata/wsl.go
  vendor/github.com/bombsimon/wsl/wsl.go
  vendor/modules.txt
Labels: question
