Repository golangci/golangci-lint, pull requests merged in 2019-12, with the labels that each got.

#874 Misc. README Updates
  README.md
  README.tmpl.md
Labels: cleanup, docs

#880 Fix depguard config in yml
  .golangci.example.yml
  .golangci.yml
  README.md
Labels: bug, config

#883 Update Trusted By section in README
  README.md
  README.tmpl.md
Labels: docs

#834 unused: suggest deleting unused stuff
  pkg/golinters/unused.go
Labels: enhancement

#900 Misc. build cleanup
  .golangci.yml
  Makefile
  README.md
  install.sh
Labels: cleanup

#902 Fix import order
  pkg/commands/cache.go
  pkg/commands/executor.go
  pkg/golinters/goanalysis/linter.go
  pkg/golinters/goanalysis/runner.go
Labels: cleanup

#903 Add zsh completion
  pkg/commands/completion.go
Labels: enhancement
