Repository golangci/golangci-lint, pull requests merged in 2019-11, with the labels that each got.

#842 Added go-mnd linter
  README.md
  go.mod
  go.sum
  pkg/golinters/gomnd.go
  pkg/lint/lintersdb/manager.go
  test/testdata/gomnd.go
  vendor/github.com/tommy-muehle/go-mnd/.editorconfig
  vendor/github.com/tommy-muehle/go-mnd/.gitignore
  vendor/github.com/tommy-muehle/go-mnd/.goreleaser.yml
  vendor/github.com/tommy-muehle/go-mnd/.travis.yml
  vendor/github.com/tommy-muehle/go-mnd/LICENSE
  vendor/github.com/tommy-muehle/go-mnd/README.md
  vendor/github.com/tommy-muehle/go-mnd/analyzer.go
  vendor/github.com/tommy-muehle/go-mnd/checks/argument.go
  vendor/github.com/tommy-muehle/go-mnd/checks/assign.go
  vendor/github.com/tommy-muehle/go-mnd/checks/case.go
  vendor/github.com/tommy-muehle/go-mnd/checks/checks.go
  vendor/github.com/tommy-muehle/go-mnd/checks/condition.go
  vendor/github.com/tommy-muehle/go-mnd/checks/operation.go
  vendor/github.com/tommy-muehle/go-mnd/checks/return.go
  vendor/github.com/tommy-muehle/go-mnd/config.go
  vendor/github.com/tommy-muehle/go-mnd/go.mod
  vendor/github.com/tommy-muehle/go-mnd/go.sum
  vendor/modules.txt
Labels: new linter

#871 Use the semantic version for go-mnd
  go.mod
  go.sum
Labels: dependency

#868 Update README.tmpl.md
  README.md
  README.tmpl.md
Labels: cleanup, docs
