Repository golangci/golangci-lint, pull requests merged in 2020-01, with the labels that each got.

#907 Update GoLand instructions in README.md
  README.md
  README.tmpl.md
Labels: cleanup, docs

#841 I473
  .golangci.example.yml
  Makefile
  README.md
  README.tmpl.md
  pkg/commands/executor.go
  pkg/config/config.go
  pkg/lint/lintersdb/enabled_set_test.go
  pkg/lint/lintersdb/manager.go
  pkg/result/processors/nolint_test.go
  scripts/gen_readme/main.go
  test/enabled_linters_test.go
Labels: enhancement

#849 Add rows.Err weather checked linter
  .golangci.yml
  README.md
  go.mod
  go.sum
  pkg/config/config.go
  pkg/golinters/rowerrcheck.go
  pkg/lint/lintersdb/manager.go
  test/testdata/rowserrcheck.go
  vendor/github.com/jingyugao/rowserrcheck/LICENSE
  vendor/github.com/jingyugao/rowserrcheck/passes/rowserr/rowserr.go
  vendor/modules.txt
Labels: new linter

#921 Update to go-critic v0.4.1
  go.mod
  go.sum
  vendor/github.com/go-critic/go-critic/checkers/mapKey_checker.go
  vendor/modules.txt
Labels: dependency

#850 add goprintffuncname linter
  README.md
  go.mod
  go.sum
  pkg/golinters/goprintffuncname.go
  pkg/lint/lintersdb/manager.go
  test/testdata/goprintffuncname.go
  vendor/github.com/jirfag/go-printf-func-name/pkg/analyzer/analyzer.go
  vendor/modules.txt
Labels: new linter

#905 Add release for android OS
  .goreleaser.yml
Labels: enhancement, installation

#904 Update golangci.com config to latest 1.22.x release
  .golangci.yml
  README.md
Labels: config

#933 Fix rowserrcheck URL
  README.md
  pkg/lint/lintersdb/manager.go
Labels: docs

#946 fix golangci.yml reference
  README.md
  README.tmpl.md
Labels: cleanup, docs
