Repository golangci/golangci-lint, pull requests merged in 2020-10, with the labels that each got.

#1380 Add tparallel linter
  go.mod
  go.sum
  pkg/golinters/tparallel.go
  pkg/lint/lintersdb/manager.go
  test/linters_test.go
  test/testdata/tparallel/happy_path_test.go
  test/testdata/tparallel/missing_subtest_test.go
  test/testdata/tparallel/missing_toplevel_test.go
Labels: linter: new

#1410 ci(nancy): Bump nancy version to 1.0.1
  .github/workflows/pr-extra.yml
Labels: hacktoberfest

#1406 Add dummy maintainer to keep `dpkg` happy
  .goreleaser.yml
Labels: hacktoberfest

#1420 Add go-errorlint
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/golinters/errorlint.go
  pkg/lint/lintersdb/manager.go
  test/testdata/errorlint.go
  test/testdata/errorlint_errorf.go
Labels: linter: new

#1424 ci(dependabot): Change interval for npm to monthly
  .github/dependabot.yml
Labels: docs, hacktoberfest, hacktoberfest-accepted, javascript

#1411 Add exhaustivestruct linter
  go.mod
  go.sum
  pkg/golinters/exhaustivestruct.go
  pkg/lint/lintersdb/manager.go
  test/testdata/exhaustivestruct.go
Labels: hacktoberfest, hacktoberfest-accepted

#1422 Update gochecknoglobals, use source analyzer
  go.mod
  go.sum
  pkg/golinters/gochecknoglobals.go
  pkg/golinters/gochecknoinits.go
  test/testdata/gochecknoglobals.go
  test/testdata/testpackage_internal_test.go
Labels: hacktoberfest, hacktoberfest-accepted

#1352 Mention macports installation procedure on macOS
  docs/src/docs/usage/install/index.mdx
Labels: hacktoberfest-accepted

#1383 Releasing docker image for arm64
  .github/workflows/tag.yml
  .goreleaser.yml
  build/Dockerfile
  build/Dockerfile.alpine
Labels: docker, enhancement, hacktoberfest, hacktoberfest-accepted
