Repository golangci/golangci-lint, pull requests merged in 2021-06, with the labels that each got.

#2039 doc: Un-deprecate enable-all option.
  .golangci.example.yml
  .golangci.yml
  docs/src/docs/usage/install/index.mdx
  pkg/commands/run.go
Labels: area: docs, enhancement

#2040 doc: add all integrations to docs introduction page
  docs/src/docs/index.mdx
Labels: area: docs, enhancement

#2043 output: generate HTML report
  pkg/commands/run.go
  pkg/config/output.go
  pkg/printers/html.go
Labels: enhancement

#2044 Add IgnoreTests to goconst configuration.
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/goconst.go
  test/testdata/goconst_dont_ignore_test.go
  test/testdata/goconst_ignore_test.go
Labels: linter: update

#2055 revive: allow to disable a rule
  pkg/config/linters_settings.go
  pkg/golinters/revive.go
Labels: enhancement

#2062 docs: update for v1.41.0
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
  go.sum
Labels: area: docs

#2065 Bump github.com/ryancurrah/gomodguard from 1.2.1 to 1.2.2
  go.mod
  go.sum
Labels: linter: update

#2064 revive: fix exclude comment rule for const block.
  pkg/config/issues.go
Labels: bug

#2066 docs: Update documentation and assets
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: area: docs

#2075 revive: add enable-all-rules.
  pkg/config/linters_settings.go
  pkg/golinters/revive.go
Labels: enhancement

#2069 gofumpt: Add lang-version option
  .golangci.example.yml
  pkg/config/linters_settings.go
  pkg/golinters/gofumpt.go
Labels: enhancement

#2077 docs: convert issue templates to issue forms.
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: area: docs, enhancement

#2080 Support RISV64
  .goreleaser.yml
  go.mod
  go.sum
Labels: enhancement

#2078 dev: fix interface implement check for "SkipDirs"
  pkg/result/processors/skip_dirs.go
  pkg/result/processors/skip_files.go
Labels: bug
