Repository golangci/golangci-lint, pull requests merged in 2021-08, with the labels that each got.

#2145 Update Wrapcheck to v2.3
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/wrapcheck.go
Labels: linter: update

#2154 Revert "add nilassign linter"
  go.mod
  go.sum
  pkg/golinters/nilassign.go
  pkg/lint/lintersdb/manager.go
  test/testdata/nilassign.go
Labels: bug

#2129 Add errname linter
  go.mod
  go.sum
  pkg/golinters/errname.go
  pkg/lint/lintersdb/manager.go
  test/testdata/errname.go
Labels: linter: new

#2117 suggest golangci-lint help linters
  pkg/lint/lintersdb/validator.go
Labels: area: docs

#2179 Bump staticcheck to 2021.1.1 (v0.2.1)
  go.mod
  go.sum
Labels: linter: update

#2182 docs: Update documentation and assets
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: area: docs

#2183 Update Go versions used by the CI
  .github/workflows/post-release.yml
  .github/workflows/pr.yml
  .github/workflows/tag.yml
Labels: enhancement, blocked, area: ci

#2187 docs: fix link to `Spacemacs`
  docs/src/docs/usage/integrations.mdx
Labels: bug, area: docs

#2188 Build docker images with go1.17
  Makefile
  build/Dockerfile
  build/Dockerfile.alpine
Labels: area: ci

#2186 go-critic: fix invalid type conversions.
  pkg/golinters/gocritic.go
Labels: bug
