Repository golangci/golangci-lint, pull requests merged in 2021-07, with the labels that each got.

#2089 docs: not show the number of linters
  docs/src/docs/index.mdx
Labels: area: docs, enhancement

#2107 cleanup: Remove completion subcommand
  pkg/commands/completion.go
  pkg/commands/executor.go
Labels: topic: cleanup

#2109 Improve goimports description
  pkg/golinters/goimports.go
Labels: area: docs, enhancement

#2110 errcheck: allow exclude config without extra file
  .golangci.example.yml
  .golangci.yml
  pkg/config/linters_settings.go
  pkg/golinters/errcheck.go
  test/testdata/errcheck/exclude_functions.yml
  test/testdata/errcheck_exclude_functions.go
Labels: enhancement

#2128 docs: improve goconst documentation.
  .golangci.example.yml
  pkg/golinters/goconst.go
Labels: area: docs, enhancement

#2131 add nilassign linter
  go.mod
  go.sum
  pkg/golinters/nilassign.go
  pkg/lint/lintersdb/manager.go
  test/testdata/nilassign.go
Labels: linter: new
