Repository golangci/golangci-lint, pull requests merged in 2021-03, with the labels that each got.

#1460 Update Docs and Assets Github Actions
  .github/workflows/post-release.yml
  .github/workflows/tag.yml
Labels: area: ci, hacktoberfest, hacktoberfest-accepted, topic: speed

#1827 docs: Update for v1.38.0
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: area: docs

#1817 Add gomoddirectives linter.
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/golinters/gomoddirectives.go
  pkg/lint/lintersdb/manager.go
  pkg/result/processors/autogenerated_exclude.go
Labels: linter: new

#1829 Bump staticcheck to 2020.2.3 (v0.1.3)
  go.mod
  go.sum
Labels: linter: update

#1819 Deprecate 'scopelint' linter
  .golangci.yml
  go.sum
  pkg/golinters/gofmt_common.go
  pkg/lint/lintersdb/manager.go
  pkg/result/processors/fixer.go
  pkg/result/processors/path_prefixer_test.go
  test/run_test.go
  test/testdata/scopelint.go
Labels: linter: update

#1830 Clean configuration and code
  .golangci.yml
  pkg/config/config_gocritic.go
  pkg/config/config_gocritic_test.go
  pkg/golinters/depguard.go
  pkg/golinters/goanalysis/adapters.go
  pkg/golinters/gochecknoglobals.go
  pkg/golinters/unparam.go
  pkg/result/processors/max_from_linter_test.go
  pkg/result/processors/processor_test.go
  scripts/expand_website_templates/main.go
  test/testdata/fix/in/gofumpt.go
  test/testdata/fix/out/gofumpt.go
Labels: topic: cleanup

#1834 bump gofumpt from v0.1.0 to v0.1.1
  go.mod
  go.sum
Labels: bug, linter: update

#1837 Update ifshort to v1.0.2
  go.mod
  go.sum
Labels: linter: update

#1838 dev: remove old TODO and remove assert import alias on require.
  test/fix_test.go
  test/linters_test.go
Labels: topic: cleanup

#1840 docs: adding missing format options
  .golangci.example.yml
Labels: area: docs

#1583 nolintlint: allow to fix //nolint lines
  pkg/golinters/nolintlint.go
  pkg/golinters/nolintlint/nolintlint.go
  pkg/golinters/nolintlint/nolintlint_test.go
  pkg/result/issue.go
  pkg/result/processors/nolint.go
  pkg/result/processors/nolint_test.go
  pkg/result/processors/testdata/nolint_unused.go
  test/testdata/fix/in/nolintlint.go
  test/testdata/fix/out/nolintlint.go
  test/testdata/nolintlint.go
Labels: linter: update

#1842 docs: improve linters page
  pkg/golinters/errorlint.go
  pkg/lint/lintersdb/manager.go
  scripts/expand_website_templates/main.go
Labels: area: docs, enhancement

#1844 Restore fast linters meaning
  pkg/lint/linter/config.go
  pkg/lint/lintersdb/manager.go
Labels: bug

#1843 Bump rowserrcheck to HEAD
  go.mod
  go.sum
Labels: linter: update

#1847 Add new presets
  pkg/lint/linter/config.go
  pkg/lint/lintersdb/manager.go
Labels: enhancement

#1854 Add versions, improve deprecation system, improve linters page
  docs/src/docs/contributing/new-linters.mdx
  pkg/lint/linter/config.go
  pkg/lint/lintersdb/manager.go
  pkg/lint/runner.go
  scripts/expand_website_templates/main.go
Labels: area: docs

#1862 fix: wrong linters load mode
  pkg/golinters/forcetypeassert.go
  pkg/golinters/ineffassign.go
  pkg/golinters/makezero.go
  pkg/golinters/paralleltest.go
  pkg/golinters/unused.go
  pkg/lint/lintersdb/manager.go
  test/testdata/asciicheck.go
Labels: bug, topic: speed

#1863 Bump wrapcheck to v1.0.0
  go.mod
  go.sum
Labels: linter: update

#1865 Bump makezero to HEAD
  go.mod
  go.sum
Labels: linter: update

#1864 Bump importas to HEAD
  go.mod
  go.sum
Labels: linter: update

#1869 Set version command output to Stdout
  pkg/commands/version.go
Labels: bug

#1870 typo fixes in architecture.mdx
  docs/src/docs/contributing/architecture.mdx
Labels: area: docs

#1871 docs: add cache directory information.
  docs/src/docs/usage/configuration.mdx
Labels: area: docs

#1861 typecheck: display compilation errors as report instead of error
  go.mod
  go.sum
  pkg/golinters/goanalysis/errors.go
  pkg/golinters/goanalysis/linter.go
  pkg/golinters/goanalysis/metalinter.go
  pkg/golinters/goanalysis/runner.go
  pkg/golinters/goanalysis/runner_action.go
  pkg/golinters/goanalysis/runner_facts.go
  pkg/golinters/goanalysis/runner_loadingpackage.go
  pkg/golinters/goanalysis/runners.go
  pkg/golinters/typecheck.go
  pkg/lint/linter/config.go
  pkg/lint/lintersdb/enabled_set.go
  pkg/lint/runner.go
  pkg/packages/util.go
  pkg/packages/util_test.go
  pkg/result/processors/max_per_file_from_linter.go
  test/testdata/notcompiles/typecheck_many_issues.go
Labels: bug

#1876 docs: update for v1.39.0
  .github/contributors/package-lock.json
  .github/contributors/rewrite_readme.ts
  .nancy-ignore
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: area: docs

#1265 Add promlinter to lint metrics name
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/golinters/promlinter.go
  pkg/lint/lintersdb/manager.go
  test/testdata/promlinter.go
Labels: linter: new
