Repository golangci/golangci-lint, pull requests merged in 2021-09, with the labels that each got.

#2213 errcheck: update to HEAD
  go.mod
  go.sum
Labels: linter: update

#2217 gci: Parse the settings more similarly to the cli
  pkg/golinters/gci.go
Labels: enhancement

#2224 docs: Update documentation and assets
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: area: docs

#2219 new-linter: ireturn (checks for function return type)
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/ireturn.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/ireturn.yml
  test/testdata/configs/ireturn_stdlib_reject.yml
  test/testdata/ireturn_allow.go
  test/testdata/ireturn_default.go
  test/testdata/ireturn_reject_stdlib.go
Labels: linter: new

#2236 Add nilnil linter
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/nilnil.go
  pkg/lint/lintersdb/manager.go
  test/testdata/nilnil.go
Labels: linter: new

#2237 nlreturn: add block-size option
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/nlreturn.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/nlreturn.yml
  test/testdata/nlreturn-block-size.go
Labels: enhancement

#2221 add tenv linter
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/tenv.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/tenv_all.yml
  test/testdata/tenv.go
  test/testdata/tenv_all.go
  test/testdata/tenv_all_test.go
  test/testdata/tenv_test.go
Labels: linter: new

#2262 fix: go.sum
  go.sum
Labels: bug

#2264 add support for finding issues in entire files in a diff
  go.mod
  go.sum
  pkg/commands/run.go
  pkg/config/issues.go
  pkg/lint/runner.go
  pkg/result/processors/diff.go
Labels: enhancement
