Repository golangci/golangci-lint, pull requests merged in 2021-01, with the labels that each got.

#1563 Validate gocritic settings. Return error if settings includes a unsupported gocritic checker
  pkg/config/config_gocritic.go
Labels: enhancement

#1606 add 'predeclared' linter
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/golinters/predeclared.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/predeclared.yml
  test/testdata/predeclared.go
  test/testdata/predeclared_custom.go
Labels: linter: new

#1593 fix: modules-download-mode support
  .golangci.example.yml
  go.mod
  go.sum
  pkg/lint/load.go
Labels: bug

#1638 Update docs for v1.35.0 release.
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: docs

#1637 Update mvdan.cc/gofumpt to v0.1.0
  go.mod
  go.sum
  test/linters_test.go
  test/testdata/fix/out/gofumpt.go
  test/testdata/gofumpt.go
  test/testdata/gofumpt_with_extra.go
Labels: linter: update

#1639 fix regression: update thelper to v0.2.1
  go.mod
  go.sum
  test/testdata/thelper.go
Labels: bug

#1642 bump github.com/daixiang0/gci from 0.2.7 to 0.2.8
  go.mod
  go.sum
Labels: linter: update

#1643 Update docs for v1.35.2
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: docs

#1648 Add issues.fix config to example configuration
  .golangci.example.yml
Labels: docs

#1595 Verify linter name in integration tests
  pkg/printers/text.go
  test/errchk.go
  test/linters_test.go
  test/testdata/asciicheck.go
  test/testdata/default_exclude.go
  test/testdata/exportloopref.go
  test/testdata/forbidigo.go
  test/testdata/funlen.go
  test/testdata/go-header_bad.go
  test/testdata/gocritic.go
  test/testdata/godox.go
  test/testdata/goerr113.go
  test/testdata/gofmt_no_simplify.go
  test/testdata/gomnd.go
  test/testdata/gomodguard.go
  test/testdata/govet.go
  test/testdata/nestif.go
  test/testdata/noctx.go
  test/testdata/nolintlint_unused.go
  test/testdata/staticcheck_in_megacheck.go
  test/testdata/stylecheck_not_in_megacheck.go
  test/testdata/thelper.go
Labels: area: tests

#1587 Add ifshort linter
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/config.go
  pkg/golinters/ifshort.go
  pkg/lint/lintersdb/manager.go
  test/testdata/ifshort.go
Labels: feedback required, linter: new

#1667 fix: bump github.com/tommy-muehle/go-mnd/v2 to v2.3.1
  go.mod
  go.sum
  pkg/golinters/gomnd.go
Labels: linter: update

#1668 Update docs for v1.36.0
  CHANGELOG.md
  README.md
  assets/github-action-config.json
Labels: docs

#1669 Add "exclude" option for godot linter
  .golangci.example.yml
  pkg/config/config.go
  pkg/golinters/godot.go
Labels: linter: update

#1670 fix rowserrcheck reports false positive
  go.mod
  go.sum
  test/testdata/rowserrcheck.go
Labels: linter: update

#1671 Update ifshort to v1.0.1
  .golangci.example.yml
  go.mod
  go.sum
Labels: linter: update
