Repository golangci/golangci-lint, pull requests merged in 2021-11, with the labels that each got.

#2318 Replace ioutil with io and os
  internal/cache/cache.go
  internal/cache/cache_test.go
  internal/cache/default.go
  internal/cache/hash_test.go
  internal/renameio/renameio.go
  internal/renameio/renameio_test.go
  internal/renameio/umask_test.go
  internal/robustio/robustio.go
  internal/robustio/robustio_flaky.go
  internal/robustio/robustio_other.go
  pkg/commands/run.go
  pkg/fsutils/filecache.go
  pkg/golinters/gofumpt.go
  pkg/golinters/gosec.go
  pkg/golinters/revive.go
  pkg/result/processors/diff.go
  scripts/expand_website_templates/main.go
  test/errchk.go
  test/fix_test.go
  test/linters_test.go
  test/testshared/testshared.go
Labels: topic: cosmetic

#2319 .golangci.example.yml: clarify nolintlint.allow-unused
  .golangci.example.yml
Labels: enhancement, area: docs

#2310 fix: Add missing space in "disabled by config" warning
  pkg/config/linters_settings_gocritic.go
Labels: topic: cleanup

#2338 cli: don't hide enable-all option
  pkg/commands/run.go
Labels: bug

#2340 preallocate slices
  pkg/commands/help.go
  pkg/golinters/wsl.go
  pkg/printers/codeclimate.go
  pkg/result/processors/nolint.go
  pkg/timeutils/stopwatch.go
Labels: enhancement

#2341 Change Github to GitHub in comments and docs
  .golangci.example.yml
  README.md
  docs/src/docs/index.mdx
  pkg/printers/github.go
Labels: area: docs

#2308 gocritic: add support for variable substitution in ruleguard path settings
  .golangci.example.yml
  go.mod
  go.sum
  pkg/commands/executor.go
  pkg/commands/linters.go
  pkg/commands/run.go
  pkg/config/config.go
  pkg/config/reader.go
  pkg/config/run.go
  pkg/golinters/gocritic.go
  test/linters_test.go
  test/ruleguard/README.md
  test/ruleguard/dup.go
  test/ruleguard/strings_simplify.go
  test/testdata/configs/gocritic.yml
  test/testdata/gocritic.go
Labels: enhancement

#2304 Add documentation for go-critic and ruleguard settings
  .golangci.example.yml
Labels: enhancement, area: docs

#2330 Add github.com/breml/bidichk linter
  go.mod
  go.sum
  pkg/golinters/bidichk.go
  pkg/lint/lintersdb/manager.go
  test/testdata/bidichk.go
Labels: linter: new

#2344 exhaustive: upgrade to latest tag; add new flags and deprecate old ones
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/exhaustive.go
  test/testdata/configs/exhaustive_checking_strategy_name.yml
  test/testdata/configs/exhaustive_checking_strategy_value.yml
  test/testdata/configs/exhaustive_ignore_enum_members.yml
  test/testdata/exhaustive_checking_strategy_name.go
  test/testdata/exhaustive_checking_strategy_value.go
  test/testdata/exhaustive_default.go
  test/testdata/exhaustive_ignore_enum_members.go
Labels: linter: update

#2348 bump varnamelen from v0.3.0 to v0.4.0
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/varnamelen.go
Labels: linter: update

#2347 bump bidichk from v0.1.1 to v0.2.0
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/bidichk.go
  pkg/lint/lintersdb/manager.go
Labels: linter: update

#2351 docs: fix a typo and a syntax error in architecture.mdx
  docs/src/docs/contributing/architecture.mdx
Labels: area: docs

#2352 Fix grammar issues in comments
  internal/cache/cache.go
  internal/cache/cache_test.go
  internal/pkgcache/pkgcache.go
  internal/robustio/robustio_flaky.go
  pkg/commands/run.go
  pkg/golinters/goanalysis/runner.go
  pkg/golinters/goanalysis/runner_action.go
  pkg/golinters/goanalysis/runner_loadingpackage.go
  pkg/golinters/gochecknoglobals.go
  pkg/golinters/lll.go
  pkg/golinters/nolintlint/nolintlint.go
  pkg/golinters/revive.go
  pkg/lint/load.go
  pkg/lint/runner.go
  pkg/logutils/log.go
  pkg/packages/util.go
  pkg/result/processors/nolint.go
  pkg/result/processors/sort_results.go
Labels: area: docs

#2359 fix: reduce flaky in the CI and clean the .golangci.yml of the project
  .golangci.yml
  pkg/commands/run.go
  pkg/config/config.go
  pkg/golinters/gocritic.go
  pkg/lint/lintersdb/validator.go
  pkg/packages/errors.go
  pkg/timeutils/stopwatch.go
  test/bench/bench_test.go
Labels: topic: cleanup, area: ci

#2358 Ensure that the Issues key in JSON format is a list
  pkg/printers/json.go
Labels: enhancement

#2350 Show deprecated mark in the CLI linters help
  pkg/commands/help.go
Labels: enhancement, feedback required

#2360 chore: fix wrong default value in comment
  .golangci.example.yml
Labels: area: docs

#2364 Reused exit codes
  pkg/commands/cache.go
  pkg/commands/config.go
  pkg/commands/help.go
  pkg/commands/linters.go
  pkg/commands/root.go
  pkg/config/reader.go
Labels: topic: cleanup

#2366 Clean up and used iota for exit codes
  pkg/exitcodes/exitcodes.go
Labels: topic: cosmetic

#2369 bump varnamelen from v0.4.0 to v0.5.0
  .golangci.example.yml
  go.mod
  go.sum
  pkg/golinters/gocritic.go
  pkg/golinters/godot.go
Labels: linter: update

#2362 Add errchkjson linter
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/errchkjson.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/errchkjson.yml
  test/testdata/configs/errchkjson_check_error_free_encoding.yml
  test/testdata/configs/errchkjson_no_exported.yml
  test/testdata/errchkjson.go
  test/testdata/errchkjson_check_error_free_encoding.go
  test/testdata/errchkjson_no_exported.go
Labels: linter: new

#2379 Update wrapcheck configuration to include ignoreSignRegexps
  .golangci.example.yml
  pkg/config/linters_settings.go
  pkg/golinters/wrapcheck.go
Labels: enhancement
