Repository golangci/golangci-lint, pull requests merged in 2022-12, with the labels that each got.

#3397 Revert "build(deps): bump github.com/shirou/gopsutil/v3 from 3.22.10 to 3.22.11"
  go.mod
  go.sum
Labels: dependencies

#3405 feat: remove deprecated linters from presets
  pkg/lint/lintersdb/manager.go
Labels: enhancement, area: presets

#3349 doc: improve documentation for goimport local-prefixes
  .golangci.reference.yml
  pkg/golinters/goimports.go
Labels: enhancement, area: docs

#3377 doc: cache preserving and colored output on docker runs
  docs/src/docs/usage/install/index.mdx
Labels: enhancement, area: docs

#3423 doc: usage typo in tagliatelle
  .golangci.reference.yml
Labels: area: docs

#3429 unparam: bump to HEAD
  go.mod
  go.sum
Labels: dependencies, linter: update version, go

#3369 Add the ginkgolinter linter
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/ginkgolinter.go
  pkg/lint/lintersdb/manager.go
  test/linters_test.go
  test/testdata/ginkgolinter/configs/ginkgolinter_default.yml
  test/testdata/ginkgolinter/configs/ginkgolinter_suppress_err.yml
  test/testdata/ginkgolinter/configs/ginkgolinter_suppress_len.yml
  test/testdata/ginkgolinter/configs/ginkgolinter_suppress_nil.yml
  test/testdata/ginkgolinter/ginkgolinter.go
  test/testdata/ginkgolinter/ginkgolinter_suppress_err.go
  test/testdata/ginkgolinter/ginkgolinter_suppress_len.go
  test/testdata/ginkgolinter/ginkgolinter_suppress_nil.go
  test/testdata/ginkgolinter/go.mod
  test/testdata/ginkgolinter/go.sum
Labels: linter: new

#3418 doc: More specific default cache directory
  docs/src/docs/usage/configuration.mdx
Labels: enhancement, area: docs

#3434 doc: improve documentation about debugging.
  docs/src/docs/contributing/debug.mdx
  pkg/logutils/logutils.go
Labels: enhancement, area: docs

#3442 Build NetBSD binaries
  .goreleaser.yml
  install.sh
Labels: enhancement, area: ci
