Repository golangci/golangci-lint, pull requests merged in 2022-05, with the labels that each got.

#2829 docs: update "Shell Completion" instruction on Linux
  docs/src/docs/usage/integrations.mdx
Labels: enhancement, area: docs

#2833 docs: Update documentation and assets
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: area: docs

#2841 docs: add missing linters
  .golangci.example.yml
Labels: bug, area: docs

#2842 errchkjson: fix typo
  pkg/golinters/errchkjson.go
Labels: bug, area: docs

#2845 bump github.com/lufeee/execinquery from v1.0.0 to v1.2.0
  go.mod
  go.sum
  pkg/golinters/execinquery.go
  pkg/lint/lintersdb/manager.go
  test/testdata/execinquery.go
Labels: bug, linter: update version

#2846 docs: Update documentation and assets
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: area: docs

#2853 bump github.com/lufeee/execinquery from v1.2.0 to v1.2.1
  go.mod
  go.sum
Labels: bug, linter: update version

#2857 docs: rename .golangci.example.yml to .golangci.reference.yml
  .golangci.reference.yml
  docs/src/docs/contributing/faq.mdx
  docs/src/docs/contributing/new-linters.mdx
  docs/src/docs/contributing/workflow.mdx
  docs/src/docs/usage/configuration.mdx
  scripts/expand_website_templates/main.go
  scripts/expand_website_templates/main_test.go
Labels: enhancement, area: docs, area: config

#2855 bump github.com/polyfloyd/go-errorlint to v1.0.0
  go.mod
  go.sum
Labels: linter: update version

#2854 thelper: allow to disable one option
  pkg/config/linters_settings.go
  pkg/golinters/thelper.go
  test/testdata/configs/thelper.yml
  test/testdata/thelper_with_options.go
Labels: bug, linter: update

#2860 docs: Update documentation and assets
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: area: docs

#2865 chore: spelling and grammar fixes
  pkg/fsutils/linecache.go
  pkg/golinters/gofmt_common.go
  pkg/golinters/gosimple.go
Labels: topic: cosmetic

#2867 docs: fix typo
  CHANGELOG.md
Labels: area: docs

#2882 fix: codeQL scanning
  .nancy-ignore
Labels: bug, area: ci

#2891 docs(linters): add defaults
  .golangci.reference.yml
Labels: enhancement, area: docs, area: config

#2890 docs(govet): add settings for `shadow` and `unusedresult`
  .golangci.reference.yml
Labels: enhancement, area: docs, area: config

#2887 docs(thelper): add `fuzz` config and description
  .golangci.reference.yml
Labels: enhancement, area: docs, area: config

#2886 docs(gosec): add configs for all existing rules
  .golangci.reference.yml
Labels: enhancement, area: docs, area: config

#2884 docs(depguard): add `ignore-file-rules`
  .golangci.reference.yml
Labels: enhancement, area: docs, area: config

#2885 docs(gocritic): add `enable` and `disable` ruleguard settings
  .golangci.reference.yml
Labels: enhancement, area: docs, area: config

#2892 gci: fix issues and re-enable autofix
  go.mod
  go.sum
  pkg/golinters/gci.go
  pkg/golinters/gofmt_common.go
  test/linters_test.go
  test/testdata/fix/in/gci.go
  test/testdata/fix/out/gci.go
Labels: linter: update version, linter: update
