Repository golangci/golangci-lint, pull requests merged in 2022-11, with the labels that each got.

#3345 docs: fix typo in nolint
  pkg/golinters/nolintlint/README.md
Labels: area: docs

#3307 doc: improve Editor Integration section
  docs/src/docs/usage/integrations.mdx
Labels: enhancement, area: docs

#3350 build(deps): bump github.com/sourcegraph/go-diff to HEAD
  go.mod
  go.sum
Labels: bug, dependencies

#3355 chore: Add a clarifying note to the bug report template
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: enhancement, area: ci

#3372 build(deps): bump github.com/leonklingele/grouper from 1.1.0 to 1.1.1
  go.mod
  go.sum
Labels: dependencies, linter: update version

#3378 build(deps): bump github.com/timakin/bodyclose to HEAD
  go.mod
  go.sum
Labels: dependencies, go
