Repository golangci/golangci-lint, pull requests merged in 2022-10, with the labels that each got.

#3278 fix: remove redundant character escape '\/'
  pkg/fsutils/path_unix.go
  pkg/fsutils/path_windows.go
  pkg/golinters/depguard.go
  pkg/result/processors/exclude_rules.go
  pkg/result/processors/path_unix.go
  pkg/result/processors/path_windows.go
  pkg/result/processors/severity_rules.go
  pkg/result/processors/skip_dirs.go
  pkg/result/processors/skip_files.go
  test/testshared/runner.go
  test/testshared/runner_unix.go
  test/testshared/runner_windows.go
Labels: bug, platform: windows

#3284 revive: fix configuration parsing
  .golangci.reference.yml
  go.mod
  go.sum
Labels: bug, area: config

#3288 lll: skip imports
  pkg/golinters/lll.go
  test/testdata/configs/lll_import.yml
  test/testdata/lll_multi_import.go
  test/testdata/lll_single_import.go
Labels: enhancement, linter: update

#3300 chore: update go.mod for gen_github_action_config script
  scripts/gen_github_action_config/go.mod
  scripts/gen_github_action_config/go.sum
  scripts/gen_github_action_config/main.go
Labels: topic: cleanup, area: ci

#3302 doc: improved wording
  docs/src/docs/usage/configuration.mdx
Labels: enhancement, area: docs

#3294 code-climate: add default severity
  pkg/printers/checkstyle.go
  pkg/printers/codeclimate.go
  pkg/printers/codeclimate_test.go
  pkg/printers/github_test.go
Labels: enhancement, area: output

#3315 docs(gomnd): add missing always ignored functions
  .golangci.reference.yml
Labels: enhancement, area: docs
