Repository golangci/golangci-lint, pull requests merged in 2022-01, with the labels that each got.

#2388 fix: update uname_os from shlib in install.sh
  install.sh
Labels: bug, platform: windows

#2450 gocritic: support autofix
  Makefile
  pkg/golinters/gocritic.go
  test/ruleguard/rangeExprCopy.go
  test/testdata/fix/in/gocritic.go
  test/testdata/fix/out/gocritic.go
Labels: enhancement

#2458 doc: improve revive documentation
  .golangci.example.yml
Labels: enhancement, area: docs

#2457 dev: improve and clean fix_test
  test/fix_test.go
  test/testdata/configs/gocritic-fix.yml
  test/testdata/fix/in/gocritic.go
  test/testdata/fix/in/unused.go
  test/testdata/fix/out/gocritic.go
  test/testdata/fix/out/unused.go
Labels: enhancement, area: tests

#2386 Add support for multiple outputs
  .golangci.example.yml
  pkg/commands/run.go
  pkg/printers/checkstyle.go
  pkg/printers/codeclimate.go
  pkg/printers/github.go
  pkg/printers/html.go
  pkg/printers/json.go
  pkg/printers/junitxml.go
  pkg/printers/tab.go
  pkg/printers/text.go
  test/linters_test.go
  test/testshared/testshared.go
Labels: enhancement, area: config

#2453 Add decorder linter
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/decorder.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/decorder.yml
  test/testdata/decorder.go
  test/testdata/decorder_default.go
Labels: linter: new

#2460 Print error text in <failure> tag content for more readable junit report
  pkg/printers/junitxml.go
Labels: enhancement

#2463 pkg/result/processors: compile nolint regexp only once
  pkg/result/processors/nolint.go
Labels: enhancement, topic: speed

#2467 depguard: updates configuration
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/depguard.go
  test/testdata/configs/depguard_additional_guards.yml
  test/testdata/configs/depguard_ignore_file_rules.yml
  test/testdata/depguard_additional_guards.go
  test/testdata/depguard_ignore_file_rules.go
Labels: enhancement, linter: update

#2482 exhaustive: drop deprecated/unused settings
  pkg/config/linters_settings.go
  pkg/golinters/exhaustive.go
Labels: enhancement, linter: update

#2483 godot: add period option
  .golangci.example.yml
  pkg/config/linters_settings.go
  pkg/golinters/godot.go
Labels: enhancement, linter: update

#2471 Return error if any linter fails to run
  pkg/lint/runner.go
Labels: enhancement

#2487 Bump github.com/ashanbrown/forbidigo from 1.2.0 to 1.3.0
  go.mod
  go.sum
  test/testdata/configs/forbidigo.yml
  test/testdata/forbidigo_example.go
Labels: enhancement, linter: update

#2490 Bump makezero to v1.1.0
  go.mod
  go.sum
  test/testdata/makezero.go
Labels: linter: update

#2495 dev: rename `rowserrcheck` linter file to match linter name.
  pkg/golinters/rowserrcheck.go
Labels: topic: cosmetic

#2435 Add maintidx linter
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/maintidx.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/maintidx_under_100.yml
  test/testdata/maintidx.go
  test/testdata/maintidx_under_100.go
Labels: linter: new

#2496 varnamelen: explicit default values
  .golangci.example.yml
  pkg/config/linters_settings.go
Labels: linter: update

#2498 gomnd: new configuration
  .golangci.example.yml
  .golangci.yml
  pkg/config/linters_settings.go
  pkg/golinters/gomnd.go
  pkg/lint/lintersdb/manager.go
Labels: enhancement, linter: update

#2382 add containedctx linter
  go.mod
  go.sum
  pkg/golinters/containedctx.go
  pkg/lint/lintersdb/manager.go
  test/testdata/containedctx.go
Labels: linter: new

#2494 importas: new option `no-extra-aliases`
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/importas.go
Labels: enhancement, linter: update

#2500 bump github.com/yeya24/promlinter from v0.1.0 to HEAD
  go.mod
  go.sum
Labels: linter: update

#2499 docs: improve linters settings section
  .golangci.example.yml
Labels: enhancement, area: docs, topic: cleanup

#2484 docs: split configuration page into multiple sections
  .golangci.yml
  docs/package-lock.json
  docs/src/docs/usage/configuration.mdx
  scripts/expand_website_templates/main.go
  scripts/expand_website_templates/main_test.go
Labels: enhancement, area: docs

#2503 importas: fix no-extra-aliases
  pkg/golinters/importas.go
Labels: bug

#2501 docs: improve configuration file content
  .golangci.example.yml
Labels: enhancement, area: docs

#2502 docs: improve page about false-positive
  docs/src/docs/usage/false-positives.mdx
Labels: enhancement, area: docs

#2506 unparam: bump to HEAD
  go.mod
  go.sum
Labels: linter: update

#2507 errorlint: bump to HEAD
  go.mod
  go.sum
Labels: linter: update

#2508 bodyclose: bump to HEAD
  go.mod
  go.sum
Labels: linter: update

#2509 ineffassign: bump to HEAD
  go.mod
  go.sum
Labels: linter: update

#2510 asciicheck: bump to v0.1.1
  go.mod
  go.sum
Labels: linter: update

#2511 forcetypeassert: bump to v0.1.0
  go.mod
  go.sum
Labels: linter: update

#2514 docs: improve configuration file content
  .golangci.example.yml
Labels: enhancement, area: docs

#2497 Add "grouper" linter
  .golangci.example.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/grouper.go
  pkg/lint/lintersdb/manager.go
Labels: linter: new

#2520 docs(revive): fix typo on the option `disabled`
  .golangci.example.yml
Labels: bug, area: docs

#2522 docs: fix misinterpreted XML tag in changelog
  CHANGELOG.md
Labels: bug, area: docs

#2531 gocritic: fix debug output
  pkg/config/linters_settings_gocritic.go
Labels: bug
