Repository golangci/golangci-lint, pull requests merged in 2023-08, with the labels that each got.

#3922 go1.21 support
  .github/workflows/documentation.yml
  .github/workflows/post-release.yml
  .github/workflows/pr-extra.yml
  .github/workflows/pr.yml
  .github/workflows/tag.yml
  .golangci.yml
  build/Dockerfile
  build/alpine.Dockerfile
  go.mod
  pkg/config/config.go
  pkg/golinters/gocritic.go
  pkg/lint/linter/config.go
  test/fix_test.go
  test/linters_test.go
Labels: enhancement

#3995 fix: trim Go version
  pkg/lint/lintersdb/manager.go
Labels: bug, area: config

#3999 build(deps): bump github.com/quasilyte/go-ruleguard from v0.3.19 to v0.4.0
  go.mod
  go.sum
  pkg/golinters/gocritic.go
  test/fix_test.go
  test/linters_test.go
Labels: dependencies, go

#4002 plugin: temporarily hide warning about using plugins using the old API
  pkg/lint/lintersdb/custom_linters.go
Labels: blocked, linter: custom

#4005 dev: improve issue form
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: enhancement

#4008 dev: CI cleanups
  .github/workflows/pr.yml
  .github/workflows/tag.yml
Labels: area: ci

#4009 dev: packaging improvements
  .goreleaser.yml
Labels: enhancement, area: ci

#4014 dev: remove netlify
  .github/workflows/post-release.yml
  Makefile
  docs/src/docs/contributing/website.mdx
  docs/src/docs/contributing/workflow.mdx
  docs/static/CNAME
  docs/template_data.state
  netlify.toml
  scripts/expand_website_templates/main.go
Labels: enhancement, area: docs

#4028 govet: add directive and slog passes
  .golangci.reference.yml
  pkg/golinters/govet.go
Labels: enhancement, linter: update

#4034 fix: add all directories as safe git directories inside the Docker image
  build/Dockerfile
  build/alpine.Dockerfile
Labels: bug, area: docker

#4035 docs: Update documentation and assets
  .github/workflows/pr.yml
  .golangci.yml
  CHANGELOG.md
  README.md
  assets/github-action-config.json
Labels: area: docs

#4048 docs: fix a typo
  pkg/logutils/logutils.go
Labels: area: docs
