Repository golangci/golangci-lint, pull requests merged in 2023-12, with the labels that each got.

#4261 build(deps): github.com/macabu/inamedparam from 0.1.2 to 0.1.3
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/inamedparam.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/inamedparam_skip_single_param.yml
  test/testdata/inamedparam_skip_single_param.go
Labels: dependencies, linter: update version, go

#4271 docs: improve .golangci.reference.yml defaults
  .golangci.reference.yml
  pkg/commands/root.go
  pkg/commands/run.go
Labels: enhancement, area: docs

#4274 docs: update link
  pkg/printers/github.go
Labels: area: docs

#4277 docs: fix Go version fallback
  .golangci.reference.yml
Labels: enhancement, area: docs

#4280 doc: fix URL not available
  docs/src/docs/contributing/website.mdx
Labels: area: docs

#4279 fix: make versioning inside Docker image consistent with binaries
  build/Dockerfile
  build/alpine.Dockerfile
Labels: bug, docker

#4275 misspell: add mode option
  .golangci.reference.yml
  pkg/config/linters_settings.go
  pkg/golinters/misspell.go
Labels: enhancement, linter: update

#4285 doc: add missing fields to .golangci.reference.yml
  .golangci.reference.yml
Labels: enhancement, area: docs

#4291 dev: replace hashicorp/go-multierror with errors.Join
  go.mod
  go.sum
  pkg/golinters/goanalysis/runner_action.go
  pkg/lint/lintersdb/custom_linters.go
  pkg/lint/runner.go
Labels: topic: cleanup
