Repository golangci/golangci-lint, pull requests merged in 2023-02, with the labels that each got.

#3414 go1.20 support
  .github/workflows/post-release.yml
  .github/workflows/pr-extra.yml
  .github/workflows/pr.yml
  .github/workflows/tag.yml
  build/Dockerfile
  build/alpine.Dockerfile
  go.mod
  go.sum
  pkg/golinters/goanalysis/runner_loadingpackage.go
  pkg/golinters/gofmt_common.go
  pkg/lint/lintersdb/manager.go
  pkg/lint/load.go
  pkg/lint/runner.go
  test/testdata/notcompiles/typecheck_many_issues.go
Labels: enhancement

#3539 docs: Update documentation and assets
  CHANGELOG.md
  README.md
  assets/github-action-config.json
  docs/template_data.state
Labels: area: docs

#3540 dev: use Go1.20 to run tests with the latest golangci-lint version
  .github/workflows/pr.yml
Labels: area: ci

#3553 ginkgolinter: fix panic
  go.mod
  go.sum
Labels: bug, linter: update version

#3550 ineffassign: bump to HEAD
  go.mod
  go.sum
Labels: dependencies, linter: update version, go

#3551 staticcheck: bump to v0.4.0
  .golangci.yml
  go.mod
  go.sum
  pkg/golinters/unused.go
Labels: dependencies, linter: update version, go

#3560 build(deps): bump github.com/go-toolsmith/astcopy from v1.0.2 to v1.0.3
  go.mod
  go.sum
Labels: bug, dependencies, go

#3558 dev: replace deprecated command with environment file
  .github/workflows/tag.yml
Labels: enhancement, area: ci

#3584 docs: Replace links to godoc.org with pkg.go.dev
  docs/src/docs/contributing/architecture.mdx
  docs/src/docs/contributing/workflow.mdx
  docs/src/docs/usage/configuration.mdx
  docs/src/docs/usage/performance.mdx
  pkg/lint/lintersdb/manager.go
  pkg/result/processors/autogenerated_exclude.go
Labels: enhancement, area: docs

#3593 docs: remove trailing whitespaces
  .golangci.reference.yml
Labels: area: docs, topic: cosmetic

#3596 dev: do not print extra whitespace in deprecated lint log
  pkg/lint/runner.go
Labels: area: docs, topic: cosmetic

#3602 govet: enable timeformat by default
  pkg/golinters/govet.go
Labels: enhancement, linter: update

#3585 dev: add new source archive
  .goreleaser.yml
Labels: enhancement, area: ci

#3608 dev: remove duplicated test asserts
  test/testshared/runner_test.go
Labels: topic: cleanup, area: tests

#3611 fix: cache status size calculation
  pkg/commands/cache.go
Labels: bug, area: cache

#3610 doc: improve installation section
  docs/src/docs/usage/install/index.mdx
Labels: area: docs, area: install

#3604 dev: replace pkg/errors with native error wrapping
  go.mod
  internal/cache/cache.go
  internal/pkgcache/pkgcache.go
  pkg/commands/executor.go
  pkg/commands/run.go
  pkg/config/linters_settings.go
  pkg/fsutils/filecache.go
  pkg/fsutils/linecache.go
  pkg/golinters/dupl.go
  pkg/golinters/errcheck.go
  pkg/golinters/forbidigo.go
  pkg/golinters/gci.go
  pkg/golinters/goanalysis/errors.go
  pkg/golinters/goanalysis/linter.go
  pkg/golinters/goanalysis/metalinter.go
  pkg/golinters/goanalysis/runner.go
  pkg/golinters/goanalysis/runner_action.go
  pkg/golinters/goanalysis/runner_loadingpackage.go
  pkg/golinters/gocritic.go
  pkg/golinters/gofmt.go
  pkg/golinters/gofmt_common.go
  pkg/golinters/gofumpt.go
  pkg/golinters/goimports.go
  pkg/golinters/gosec.go
  pkg/golinters/makezero.go
  pkg/golinters/revive.go
  pkg/golinters/whitespace.go
  pkg/goutil/env.go
  pkg/lint/load.go
  pkg/lint/runner.go
  pkg/packages/errors.go
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/cgo.go
  pkg/result/processors/fixer.go
  pkg/result/processors/issues.go
  pkg/result/processors/skip_dirs.go
Labels: topic: cleanup

#3572 lll: skip go command
  pkg/golinters/lll.go
  test/testdata/lll.go
Labels: bug, linter: update

#3624 build(deps): bump github.com/junk1tm/musttag from 0.4.5 to 0.5.0
  go.mod
  go.sum
  test/testdata/musttag.go
  test/testdata/musttag_custom.go
Labels: dependencies, linter: update version, go

#3632 dev: bytes.NewBuffer/bytes.NewBufferString to shorten initialization
  pkg/commands/executor.go
  pkg/golinters/gofumpt.go
  scripts/expand_website_templates/main.go
Labels: enhancement, topic: cleanup

#3641 dev: git ignore golangci-lint.exe on Windows
  .gitignore
Labels: enhancement, topic: cleanup

#3642 dev: remove github.com/pkg/errors inside tests
  .golangci.reference.yml
  test/testdata/configs/importas.yml
  test/testdata/configs/importas_strict.yml
  test/testdata/fix/in/gci.go
  test/testdata/fix/out/gci.go
  test/testdata/gci.go
  test/testdata/goimports_local.go
  test/testdata/importas.go
  test/testdata/importas_strict.go
Labels: topic: cleanup, area: tests

#3506 docs: Clarify that custom linters are not enabled by default
  docs/src/docs/contributing/new-linters.mdx
Labels: area: docs, linter: custom
