Repository golangci/golangci-lint, pull requests merged in 2023-03, with the labels that each got.

#3645 doc: add Tekton in Trusted By page
  docs/src/docs/product/trusted-by.mdx
Labels: enhancement, area: docs

#3625 dev: add Go version to version information
  cmd/golangci-lint/main.go
  cmd/golangci-lint/mod_version.go
  pkg/commands/executor.go
  pkg/commands/root.go
  pkg/commands/version.go
  pkg/config/config.go
Labels: enhancement, area: CLI

#3651 doc: replace golang with Go in descriptions for gci, thelper, goerr113
  pkg/golinters/gci.go
  pkg/golinters/goerr113.go
  pkg/golinters/thelper.go
Labels: enhancement, area: docs

#3655 doc: remove from FAQ golangci.com mention
  docs/src/docs/usage/faq.mdx
Labels: area: docs, topic: cleanup

#3521 feat: check only changed files in pre-commit hook
  .pre-commit-hooks.yaml
Labels: enhancement, area: docs

#3667 docs: remove description for deprecated "go" option
  .golangci.reference.yml
Labels: area: docs, topic: cleanup

#3688 doc: enhance errcheck description
  pkg/golinters/errcheck.go
Labels: enhancement, area: docs

#3689 wastedassign: remove limitation related to generics support
  pkg/lint/lintersdb/manager.go
  test/testdata/sqlclosecheck.go
  test/testdata/wastedassign.go
Labels: enhancement, linter: update

#3691 rowserrcheck: remove limitation related to generics support
  pkg/lint/lintersdb/manager.go
Labels: enhancement, linter: update

#3697 godox: bump to HEAD
  go.mod
  go.sum
Labels: dependencies, linter: update version, go

#3571 fix: consider path prefix when matching path patterns
  .golangci.reference.yml
  docs/src/docs/usage/false-positives.mdx
  pkg/fsutils/files.go
  pkg/lint/runner.go
  pkg/result/processors/base_rule.go
  pkg/result/processors/exclude_rules.go
  pkg/result/processors/exclude_rules_test.go
  pkg/result/processors/path_prefixer.go
  pkg/result/processors/severity_rules.go
  pkg/result/processors/severity_rules_test.go
  pkg/result/processors/skip_dirs.go
  pkg/result/processors/skip_files.go
  pkg/result/processors/skip_files_test.go
Labels: bug, area: config

#3704 docs: remove unused from config.LintersSettings
  pkg/config/linters_settings.go
  pkg/lint/lintersdb/manager.go
Labels: bug, area: docs

#3705 docs: fix typos
  .github/CONTRIBUTING.md
  docs/gatsby-node.js
Labels: bug, area: docs

#3710 fix: improve panic management
  pkg/golinters/goanalysis/runner_action.go
Labels: bug

#3700 fix: combination of --fix and --path-prefix
  pkg/commands/run.go
  pkg/lint/runner.go
  pkg/result/processors/fixer.go
  test/fix_test.go
Labels: bug, area: auto-fix

#3713 fix(pre-commit): require_serial & pass_filenames
  .pre-commit-hooks.yaml
Labels: bug, area: pre-commit

#3458 feat: add the gosmopolitan linter
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/gosmopolitan.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/gosmopolitan_allow_time_local.yml
  test/testdata/configs/gosmopolitan_dont_ignore_tests.yml
  test/testdata/configs/gosmopolitan_escape_hatches.yml
  test/testdata/configs/gosmopolitan_scripts.yml
  test/testdata/gosmopolitan.go
  test/testdata/gosmopolitan_allow_time_local.go
  test/testdata/gosmopolitan_dont_ignore_test.go
  test/testdata/gosmopolitan_escape_hatches.go
  test/testdata/gosmopolitan_ignore_test.go
  test/testdata/gosmopolitan_scripts.go
Labels: linter: new

#3709 add tagalign linter
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/tagalign.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/tagalign_align_only.yml
  test/testdata/configs/tagalign_order_only.yml
  test/testdata/configs/tagalign_sort_only.yml
  test/testdata/tagalign.go
  test/testdata/tagalign_align_only.go
  test/testdata/tagalign_order_only.go
  test/testdata/tagalign_sort_only.go
Labels: linter: new

#3730 tests: remove go version restrictions
  pkg/lint/lintersdb/manager.go
  test/testshared/runner.go
  test/testshared/runner_test.go
Labels: enhancement, topic: cleanup, area: tests

#3744 dev: remove golangci-releaser from generated team
  .github/contributors/generate.ts
Labels: area: docs, topic: cleanup

#3740 feat: remove warning when the config file is explicitly stdin
  pkg/config/reader.go
Labels: enhancement, area: config, topic: cosmetic
