Repository golangci/golangci-lint, pull requests merged in 2024-02, with the labels that each got.

#4341 feat: implement stats per linter with a flag
  .golangci.reference.yml
  pkg/commands/run.go
  pkg/config/run.go
Labels: enhancement, area: CLI

#4284 dev: remove unrelated flags from config and linters command
  .golangci.reference.yml
  pkg/commands/config.go
  pkg/commands/linters.go
  pkg/commands/run.go
  test/testshared/runner.go
  test/testshared/runner_test.go
Labels: topic: cosmetic, area: CLI

#4272 go1.22 support
  .github/workflows/documentation.yml
  .github/workflows/post-release.yml
  .github/workflows/pr-documentation.yml
  .github/workflows/pr-extra.yml
  .github/workflows/pr.yml
  .github/workflows/tag.yml
  build/Dockerfile
  build/alpine.Dockerfile
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/reader.go
  pkg/golinters/govet_test.go
  pkg/lint/linter/config.go
  test/enabled_linters_test.go
  test/testdata/zerologlint/zerologlint.go
Labels: enhancement

#4354 docs: Update documentation and assets
  .goreleaser.yml
  CHANGELOG.md
  README.md
  assets/github-action-config.json
Labels: area: docs

#4359 build(deps): bump github.com/Antonboom/testifylint from 1.1.0 to 1.1.1
  go.mod
  go.sum
Labels: dependencies, linter: update version, go

#4362 docs: Update documentation and assets
  CHANGELOG.md
  README.md
  assets/github-action-config.json
Labels: area: docs

#4370 dev: use goreleaser to create Docker images
  .github/workflows/tag.yml
  .goreleaser.yml
  build/Dockerfile
  build/alpine.Dockerfile
  build/buildx-alpine.Dockerfile
  build/buildx.Dockerfile
Labels: enhancement, area: ci, docker

#4372 dev: refactor govet impl with slices.Contains
  pkg/golinters/govet.go
  pkg/golinters/govet_test.go
Labels: topic: cleanup

#4373 dev: fix govet.nilness lint issues
  .golangci.yml
  pkg/lint/lintersdb/manager.go
Labels: topic: cleanup

#4374 dev: handle old TODO
  .golangci.yml
  pkg/golinters/nolintlint/nolintlint.go
  pkg/lint/lintersdb/custom_linters.go
Labels: topic: cleanup

#4377 docs: explain limitation of new-from-rev and new-from-patch
  docs/src/docs/usage/faq.mdx
Labels: enhancement, area: docs

#4365 revive: add exclude option
  .golangci.reference.yml
  pkg/config/linters_settings.go
  pkg/golinters/revive.go
Labels: enhancement, linter: update

#4366 docs: improve `govet` description
  pkg/golinters/govet.go
Labels: enhancement, area: docs

#4392 dev: fix Docker image on tag
  .goreleaser.yml
Labels: bug, docker

#4378 feat: add intrange linter
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/golinters/intrange.go
  pkg/lint/lintersdb/manager.go
  test/testdata/intrange.go
Labels: linter: new

#4382 feat: add copyloopvar linter
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/golinters/copyloopvar.go
  pkg/lint/lintersdb/manager.go
  test/testdata/copyloopvar.go
Labels: linter: new

#4335 gocritic: support of enable-all and disable-all options
  .golangci.reference.yml
  pkg/config/linters_settings.go
  pkg/golinters/gocritic.go
  pkg/golinters/gocritic_test.go
  test/ruleguard/README.md
  test/ruleguard/dup.go
  test/ruleguard/preferWriteString.go
  test/ruleguard/rangeExprCopy.go
  test/ruleguard/stringsSimplify.go
  test/testdata/configs/gocritic-fix.yml
  test/testdata/configs/gocritic.yml
  test/testdata/gocritic.go
Labels: enhancement, linter: update

#4397 feat: disable copyloopvar and intrange on Go < 1.22
  pkg/commands/executor.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/golinters/govet.go
  pkg/golinters/paralleltest.go
  pkg/lint/linter/config.go
  pkg/lint/linter/linter.go
  pkg/lint/lintersdb/manager.go
  test/linters_test.go
  test/run_test.go
  test/testdata/copyloopvar.go
  test/testdata/intrange.go
Labels: enhancement, linter: update

#4401 misspell: add extra-words
  .golangci.reference.yml
  pkg/config/linters_settings.go
  pkg/golinters/misspell.go
  pkg/golinters/misspell_test.go
  test/testdata/configs/misspell_custom.yml
  test/testdata/misspell_custom.go
Labels: enhancement, linter: update

#4406 dev: install.sh fix usage message
  install.sh
Labels: area: install, topic: cosmetic

#4407 dev: install.sh remove obsolete reference to godownloader
  install.sh
Labels: topic: cleanup, area: install

#4408 install.sh: set executable bit for Unix
  install.sh
Labels: area: install, topic: cosmetic

#4409 docs: update code snippets in Architecture
  docs/src/docs/contributing/architecture.mdx
Labels: area: docs

#4404 dev: clean up Executor
  .golangci.yml
  pkg/commands/cache.go
  pkg/commands/config.go
  pkg/commands/executor.go
  pkg/commands/help.go
  pkg/commands/linters.go
  pkg/commands/root.go
  pkg/commands/run.go
  pkg/commands/version.go
  pkg/config/config.go
  pkg/config/linters_settings.go
  pkg/config/output.go
  pkg/config/reader.go
  pkg/config/run.go
  pkg/golinters/gochecknoglobals.go
  pkg/golinters/govet.go
  pkg/goutil/env.go
  pkg/lint/lintersdb/manager.go
  pkg/lint/lintersdb/validator.go
  test/bench/bench_test.go
  test/run_test.go
Labels: topic: cleanup, area: CLI

#4396 build(deps): bump github.com/denis-tingaikin/go-headerfrom 0.4.3 to 0.5.0
  go.mod
  go.sum
  pkg/golinters/goheader.go
  pkg/lint/lintersdb/manager.go
  test/testdata/configs/go-header-fix.yml
  test/testdata/fix/in/go-header_1.go
  test/testdata/fix/in/go-header_2.go
  test/testdata/fix/in/go-header_3.go
  test/testdata/fix/out/go-header_1.go
  test/testdata/fix/out/go-header_2.go
  test/testdata/fix/out/go-header_3.go
  test/testshared/directives.go
Labels: dependencies, linter: update version, go

#4416 dev: add tests on linterdb package
  pkg/lint/lintersdb/enabled_set.go
  pkg/lint/lintersdb/enabled_set_test.go
  pkg/lint/lintersdb/validator_test.go
Labels: enhancement, area: tests

#4418 dev: clean reference file
  .golangci.reference.yml
Labels: area: docs, topic: cleanup

#4412 dev: new commands system
  cmd/golangci-lint/main.go
  docs/src/docs/contributing/architecture.mdx
  pkg/commands/cache.go
  pkg/commands/config.go
  pkg/commands/executor.go
  pkg/commands/flagsets.go
  pkg/commands/help.go
  pkg/commands/internal/vibra.go
  pkg/commands/linters.go
  pkg/commands/root.go
  pkg/commands/run.go
  pkg/commands/version.go
  pkg/config/config.go
  pkg/config/loader.go
  pkg/config/output.go
  pkg/config/reader.go
  pkg/config/run.go
  pkg/lint/lintersdb/custom_linters.go
  pkg/logutils/logutils.go
  test/run_test.go
Labels: topic: cleanup, area: CLI

#4420 dev: add test on ExcludeRule and SeverityRule
  pkg/config/issues.go
  pkg/config/issues_test.go
  pkg/config/severity_test.go
Labels: enhancement, area: tests

#4431 docs: expand install manual for running website locally
  docs/src/docs/contributing/website.mdx
Labels: enhancement, area: docs
