Repository golangci/golangci-lint, pull requests merged in 2024-01, with the labels that each got.

#4292 dev: enable errorlint linter
  .golangci.yml
  pkg/commands/executor.go
  pkg/commands/run.go
  pkg/config/issues.go
  pkg/config/reader.go
  pkg/fsutils/fsutils.go
  pkg/golinters/golint.go
  pkg/golinters/lll.go
  pkg/golinters/misspell.go
  pkg/golinters/nolintlint.go
  pkg/lint/lintersdb/custom_linters.go
  pkg/packages/errors.go
  pkg/result/processors/diff.go
  pkg/result/processors/skip_files.go
Labels: topic: cleanup

#4290 feat: add `spancheck` linter
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/spancheck.go
  pkg/lint/lintersdb/manager.go
  test/linters_test.go
  test/testdata/spancheck/configs/enable_all.yml
  test/testdata/spancheck/go.mod
  test/testdata/spancheck/go.sum
  test/testdata/spancheck/spancheck_default.go
  test/testdata/spancheck/spancheck_enable_all.go
Labels: linter: new

#4299 dev: replace raw loops with funcs from slices and maps
  go.mod
  go.sum
  pkg/golinters/goanalysis/runner.go
  pkg/golinters/gocritic.go
  pkg/golinters/govet_test.go
  pkg/golinters/thelper.go
  pkg/lint/lintersdb/enabled_set.go
  pkg/printers/checkstyle.go
  pkg/printers/junitxml.go
  pkg/result/processors/nolint.go
  scripts/expand_website_templates/main.go
Labels: topic: cosmetic

#4302 docs: fix grammar
  docs/src/docs/usage/configuration.mdx
Labels: area: docs

#4306 docs: improve typecheck FAQ
  docs/src/docs/usage/faq.mdx
Labels: enhancement, area: docs

#4319 fix: parse Go RC version
  pkg/lint/lintersdb/manager.go
  pkg/lint/lintersdb/manager_test.go
Labels: bug, area: config

#4320 dev: fix typo in testdata for gochecknoglobals
  test/testdata/gochecknoglobals.go
Labels: topic: cleanup

#4326 docs: adjust wrapcheck ignoreSigs to new defaults
  .golangci.reference.yml
Labels: enhancement, area: docs

#4334 dev: check go.sum is up to date
  .github/workflows/pr.yml
  go.sum
Labels: area: ci

#4339 dev: replace mitchellh/mapstructure by go-viper/mapstructure/v2
  go.mod
  go.sum
  pkg/config/reader.go
Labels: dependencies, go

#4340 docs: adjust list from why install from source is not recommended
  docs/src/docs/usage/install/index.mdx
Labels: enhancement, area: docs
