Repository golangci/golangci-lint, pull requests merged in 2024-03, with the labels that each got.

#4419 dev: rewrite linters Manager
  docs/src/docs/contributing/architecture.mdx
  docs/src/docs/contributing/new-linters.mdx
  pkg/commands/help.go
  pkg/commands/linters.go
  pkg/commands/run.go
  pkg/commands/version.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/issues.go
  pkg/config/linters.go
  pkg/config/linters_settings.go
  pkg/config/linters_test.go
  pkg/config/loader.go
  pkg/config/severity.go
  pkg/golinters/govet.go
  pkg/lint/lintersdb/builder_linter.go
  pkg/lint/lintersdb/builder_plugin.go
  pkg/lint/lintersdb/enabled_set.go
  pkg/lint/lintersdb/enabled_set_test.go
  pkg/lint/lintersdb/manager.go
  pkg/lint/lintersdb/manager_test.go
  pkg/lint/lintersdb/validator.go
  pkg/lint/lintersdb/validator_test.go
  pkg/lint/runner.go
  pkg/result/processors/nolint_test.go
  scripts/expand_website_templates/main.go
  test/enabled_linters_test.go
Labels: enhancement, topic: cleanup

#4443 dev: adjust replacement msg for nosnakecase
  pkg/lint/lintersdb/builder_linter.go
Labels: enhancement, linter: update

#4449 build(deps): bump github.com/Antonboom/testifylint from 1.1.3 to 1.2.0
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/testifylint.go
  test/testdata/configs/testifylint_bool_compare_only.yml
  test/testdata/configs/testifylint_require_error_only.yml
  test/testdata/testifylint.go
  test/testdata/testifylint_bool_compare.go
  test/testdata/testifylint_require_error.go
Labels: dependencies, linter: update version, go

#4441 feat: automatically adjust the maximum concurrency to the container CPU quota
  go.mod
  go.sum
  pkg/commands/run.go
Labels: enhancement

#4435 dev: isolate printer code
  pkg/commands/run.go
  pkg/printers/github.go
  pkg/printers/github_test.go
  pkg/printers/printer.go
  pkg/printers/printer_test.go
  pkg/printers/testdata/golden-github-actions.txt
  pkg/printers/testdata/golden-json.json
  pkg/printers/testdata/golden-line-number.txt
  pkg/printers/testdata/in-issues.json
  pkg/printers/testdata/in-report-data.json
Labels: enhancement, topic: cleanup

#4440 dev: split post-release workflow
  .github/workflows/post-release.yml
Labels: enhancement, area: ci

#4436 feat: inactivate deprecated linters
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/deadcode.go
  pkg/golinters/exhaustivestruct.go
  pkg/golinters/golint.go
  pkg/golinters/ifshort.go
  pkg/golinters/interfacer.go
  pkg/golinters/maligned.go
  pkg/golinters/nosnakecase.go
  pkg/golinters/scopelint.go
  pkg/golinters/structcheck.go
  pkg/golinters/unconvert.go
  pkg/golinters/util.go
  pkg/golinters/varcheck.go
  pkg/lint/linter/linter.go
  pkg/lint/lintersdb/builder_linter.go
  test/testdata/configs/exhaustivestruct.yml
  test/testdata/deadcode.go
  test/testdata/exhaustivestruct.go
  test/testdata/exhaustivestruct_custom.go
  test/testdata/golint.go
  test/testdata/ifshort.go
  test/testdata/interfacer.go
  test/testdata/maligned.go
  test/testdata/nosnakecase.go
  test/testdata/scopelint.go
  test/testdata/structcheck.go
  test/testdata/varcheck.go
Labels: topic: cleanup, linter: update

#4439 fix: move show-stats field from run to output
  .golangci.reference.yml
  .golangci.yml
  pkg/commands/flagsets.go
  pkg/commands/run.go
  pkg/config/output.go
  pkg/config/run.go
Labels: area: config, topic: cleanup

#4455 docs: don't mark dupword as autofixable
  pkg/lint/lintersdb/builder_linter.go
Labels: bug, area: docs

#4456 dev: simplify exclude processors
  pkg/lint/runner.go
  pkg/result/processors/base_rule.go
  pkg/result/processors/exclude.go
  pkg/result/processors/exclude_rules.go
  pkg/result/processors/exclude_rules_test.go
  pkg/result/processors/exclude_test.go
  pkg/result/processors/severity.go
Labels: enhancement, topic: cleanup

#4461 docs: fix typo in 'e.g.'
  .golangci.reference.yml
  pkg/result/processors/cgo.go
Labels: area: docs, topic: cleanup

#4460 dev: rename function parameter `i` to `issue`
  pkg/golinters/goanalysis/issue.go
  pkg/golinters/nolintlint/nolintlint.go
  pkg/printers/tab.go
  pkg/printers/text.go
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/cgo.go
  pkg/result/processors/diff.go
  pkg/result/processors/exclude.go
  pkg/result/processors/exclude_rules.go
  pkg/result/processors/filename_unadjuster.go
  pkg/result/processors/identifier_marker.go
  pkg/result/processors/issues.go
  pkg/result/processors/max_from_linter.go
  pkg/result/processors/max_per_file_from_linter.go
  pkg/result/processors/max_same_issues.go
  pkg/result/processors/nolint.go
  pkg/result/processors/path_prettifier.go
  pkg/result/processors/path_shortener.go
  pkg/result/processors/severity.go
  pkg/result/processors/skip_dirs.go
  pkg/result/processors/skip_files.go
  pkg/result/processors/source_code.go
  pkg/result/processors/uniq_by_line.go
Labels: enhancement, topic: cleanup

#4438 feat: allow running only a specific linter without modifying the file configuration
  pkg/commands/flagsets.go
  pkg/config/loader.go
Labels: enhancement, area: config, area: CLI

#4465 dev: add GL_DEBUG=govet to see enabled analyzers
  .golangci.reference.yml
  pkg/golinters/govet.go
  pkg/logutils/logutils.go
Labels: area: docs, linter: update

#3316 fix: use first issue without inline on mergeLineIssues on multiplie issues
  pkg/result/processors/fixer.go
  test/testdata/configs/multiple-issues-fix.yml
  test/testdata/fix/in/multiple-issues-fix.go
  test/testdata/fix/out/multiple-issues-fix.go
Labels: bug, area: auto-fix

#4466 docs: add explanation about the configuration inside repo
  .golangci.yml
Labels: area: docs, area: config

#4467 feat: add sort-order option
  .golangci.reference.yml
  pkg/commands/flagsets.go
  pkg/config/config.go
  pkg/config/output.go
  pkg/config/output_test.go
  pkg/result/processors/sort_results.go
  pkg/result/processors/sort_results_test.go
Labels: enhancement, area: output

#4473 build(deps): bump github.com/golangci/unconvert to HEAD
  .golangci.reference.yml
  go.mod
  go.sum
  pkg/config/linters_settings.go
  pkg/golinters/goanalysis/adapters.go
  pkg/golinters/unconvert.go
  pkg/lint/lintersdb/builder_linter.go
  test/linters_test.go
  test/testdata/unconvert.go
Labels: dependencies, linter: update version, go

#4470 feat: use gosec severities
  pkg/golinters/gosec.go
Labels: enhancement, linter: update, area: severity

#4468 fix: store and read severity from linters in the cache
  pkg/golinters/goanalysis/issue.go
  pkg/golinters/goanalysis/runners.go
Labels: bug, area: cache, area: severity

#4477 fix: panic when concurrency=0
  .golangci.reference.yml
  pkg/commands/run.go
Labels: bug

#4481 dev: remove unused release target
  Makefile
  tools/go.mod
  tools/go.sum
  tools/tools.go
Labels: topic: cleanup

#4480 dev: clean context loader
  pkg/commands/run.go
  pkg/lint/load.go
  pkg/lint/runner.go
Labels: topic: cleanup

#4478 dev: clean up command contructors
  pkg/commands/linters.go
  pkg/commands/root.go
  pkg/commands/run.go
  pkg/printers/json.go
  pkg/result/processors/severity_test.go
Labels: topic: cleanup, area: CLI

#4479 dev: the printer just needs Output configuration
  pkg/commands/run.go
  pkg/lint/runner.go
  pkg/printers/printer.go
  pkg/printers/printer_test.go
Labels: topic: cleanup, area: output

#4472 feat: syntax to not override severity from linters
  .golangci.reference.yml
  pkg/config/severity.go
  pkg/lint/runner.go
  pkg/result/processors/processor_test.go
  pkg/result/processors/severity.go
  pkg/result/processors/severity_test.go
Labels: enhancement, area: config, area: severity

#4484 build(deps): downgrade github.com/daixiang0/gci from 0.13.0 to 0.12.3
  .golangci.reference.yml
  go.mod
  go.sum
Labels: dependencies, linter: update version, go

#4483 dev: improve version output
  cmd/golangci-lint/main.go
Labels: enhancement, topic: cosmetic

#4487 docs: add jsonschema
  .github/workflows/post-release.yml
  jsonschema/custom-gcl.jsonschema.json
  jsonschema/golangci.jsonschema.json
  jsonschema/golangci.next.jsonschema.json
Labels: enhancement, area: JSON schema

#4489 docs: improve grammar in the custom linter article
  .custom-gcl.reference.yml
  docs/src/docs/contributing/new-linters.mdx
  docs/src/docs/plugins/module-plugins.mdx
  pkg/commands/internal/builder.go
Labels: area: docs, topic: cosmetic

#4491 dev: fix a typo in the log about preserving temp
  pkg/commands/custom.go
Labels: topic: cleanup

#4492 dev: minor clean up
  .golangci.next.reference.yml
  cmd/golangci-lint/main.go
  docs/src/docs/usage/install/index.mdx
  pkg/commands/run.go
  pkg/result/processors/severity.go
Labels: topic: cleanup

#4488 docs: publish JSON schema on golangci-lint.run
  Makefile
  docs/package.json
  docs/static/.gitignore
  jsonschema/golangci.next.jsonschema.json
Labels: area: docs, area: JSON schema

#4496 dev: use `cmd.Context` inside custom command
  cmd/golangci-lint/main.go
  pkg/commands/custom.go
Labels: topic: cleanup

#4494 docs: improve plugins page
  docs/src/config/sidebar.yml
  docs/src/docs/plugins/module-plugins.mdx
  scripts/website/expand_templates/linters.go
  scripts/website/expand_templates/main.go
  scripts/website/expand_templates/plugins.go
Labels: enhancement, area: docs

#4497 dev: display help message with green color
  pkg/commands/root.go
Labels: topic: cleanup, area: CLI

#4498 docs: improve "about golangci-lint" in README
  README.md
Labels: area: docs, topic: cleanup

#4495 dev: clean up
  pkg/config/output.go
  pkg/config/output_test.go
  pkg/result/processors/sort_results.go
  pkg/result/processors/sort_results_test.go
Labels: topic: cleanup

#4499 chore: simplify comparators
  pkg/result/processors/sort_results.go
  pkg/result/processors/sort_results_test.go
Labels: enhancement, topic: cleanup

#4500 dev: reformat code with gofumpt
  pkg/fsutils/fsutils.go
  pkg/golinters/goanalysis/runner.go
  pkg/golinters/goanalysis/runners.go
  pkg/golinters/nolintlint/nolintlint.go
  pkg/golinters/testpackage.go
  pkg/lint/load.go
  pkg/lint/runner.go
  pkg/logutils/out.go
  pkg/printers/printer.go
  pkg/result/processors/identifier_marker.go
  pkg/result/processors/identifier_marker_test.go
  pkg/result/processors/max_per_file_from_linter.go
  pkg/result/processors/nolint.go
  pkg/result/processors/nolint_test.go
  pkg/result/processors/uniq_by_line.go
  scripts/website/expand_templates/linters.go
Labels: topic: cleanup

#4505 docs: shorten description for gochecknoglobals linter
  pkg/golinters/gochecknoglobals.go
Labels: area: docs

#4502 dev: clean up
  Makefile
  scripts/website/expand_templates/main.go
Labels: topic: cleanup

#4508 docs: fix plugin example URL
  docs/src/docs/plugins/module-plugins.mdx
Labels: bug, area: docs

#4493 docs: organize sections and pages
  docs/src/config/sidebar.yml
  docs/src/docs/product/changelog.mdx
  docs/src/docs/product/performance.mdx
  docs/src/docs/product/roadmap.mdx
  docs/src/docs/usage/configuration.mdx
  docs/src/docs/welcome/annotations.png
  docs/src/docs/welcome/faq.mdx
  docs/src/docs/welcome/install.mdx
  docs/src/docs/welcome/integrations.mdx
  docs/src/docs/welcome/quick-start.mdx
  scripts/website/dump_info/main.go
  scripts/website/expand_templates/main.go
  scripts/website/types/types.go
Labels: enhancement, area: docs

#4507 feat: option to strictly follow Go autogenerated file convention
  .golangci.next.reference.yml
  jsonschema/golangci.next.jsonschema.json
  pkg/config/issues.go
  pkg/lint/runner.go
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/autogenerated_exclude_test.go
  pkg/result/processors/skip_dirs.go
  pkg/result/processors/testdata/autogen_go_strict.go
  pkg/result/processors/testdata/autogen_go_strict_invalid.go
Labels: enhancement, area: processors

#4510 build(deps): bump github.com/golangci/plugin-module-register to 0.1.0
  go.mod
  go.sum
Labels: dependencies, go, linter: custom

#4515 docs: fix installation link in the readme
  README.md
Labels: bug, area: docs

#4514 feat: rename exclude-autogenerated-strict to exclude-generated-strict
  .golangci.next.reference.yml
  jsonschema/golangci.next.jsonschema.json
  pkg/config/issues.go
  pkg/lint/runner.go
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/autogenerated_exclude_test.go
Labels: enhancement, area: processors

#4517 dev: review config path usage inside gocritic
  pkg/golinters/gocritic.go
  pkg/lint/lintersdb/builder_linter.go
Labels: topic: cleanup, linter: update

#4518 docs: fix website broken links
  docs/src/docs/contributing/workflow.mdx
  docs/src/docs/index.mdx
  docs/src/docs/welcome/faq.mdx
  docs/src/docs/welcome/install.mdx
  docs/src/docs/welcome/integrations.mdx
Labels: bug, area: docs

#4509 feat: replace `run.skip-xxx` options by `issues.exclude-xxx` options
  .golangci.next.reference.yml
  .golangci.yml
  docs/src/docs/usage/false-positives.mdx
  jsonschema/golangci.next.jsonschema.json
  pkg/commands/flagsets.go
  pkg/commands/internal/vibra.go
  pkg/commands/run.go
  pkg/config/issues.go
  pkg/config/loader.go
  pkg/config/run.go
  pkg/golinters/gochecknoglobals.go
  pkg/lint/lintersdb/manager.go
  pkg/lint/runner.go
  pkg/logutils/logutils.go
  pkg/packages/exclude.go
  pkg/packages/exclude_test.go
  test/enabled_linters_test.go
  test/run_test.go
Labels: enhancement, area: config

#4519 docs: add more tagliatelle examples
  .golangci.next.reference.yml
  .golangci.reference.yml
Labels: enhancement, area: docs

#4524 feat: create output directory
  pkg/printers/printer.go
Labels: enhancement, area: output

#4525 dev: remove Run.Args
  pkg/commands/run.go
  pkg/config/run.go
  pkg/lint/runner.go
Labels: enhancement, topic: cleanup

#4520 dev: validate test configurations
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  test/configuration_file_test.go
  test/testdata/configs/govet_fieldalignment.yml
  test/testdata/configs/govet_ifaceassert.yml
  test/testdata/configs/importas_noalias.yml
  test/testdata/configs/testifylint_bool_compare_only.yml
  test/testdata/configs/testifylint_require_error_only.yml
  test/testdata/importas_noalias.go
  test/testdata_etc/unused_exported/golangci.yml
Labels: enhancement, area: tests, area: JSON schema

#4521 feat: new output.formats file configuration syntax
  .golangci.next.reference.yml
  jsonschema/golangci.next.jsonschema.json
  pkg/commands/flagsets.go
  pkg/config/loader.go
  pkg/config/output.go
  pkg/config/output_test.go
  pkg/printers/printer.go
  pkg/printers/printer_test.go
Labels: enhancement, area: config, area: output

#4532 fix: use GOTOOLCHAIN=auto inside the Docker images
  build/buildx-alpine.Dockerfile
  build/buildx.Dockerfile
Labels: bug, area: docker, docker

#4533 fix: deprecation message related to UseDefaultSkipDirs
  pkg/config/loader.go
Labels: bug, area: config

#4534 govet: fix check-shadowing
  pkg/golinters/govet.go
Labels: bug, linter: update

#4536 feat: improve 'no go files to analyze' message
  pkg/lint/context.go
Labels: enhancement

#4535 govet: add a warning about the deprecation of check-shadowing
  .golangci.next.reference.yml
  .golangci.yml
  jsonschema/golangci.next.jsonschema.json
  pkg/config/linters_settings.go
  pkg/config/loader.go
  test/testdata/configs/govet.yml
Labels: enhancement, linter: update

#4537 dev: refactor .golangci.yml configuration and fix up nolintlint issues
  .golangci.yml
  pkg/commands/flagsets.go
  pkg/golinters/dogsled.go
  pkg/golinters/dupl.go
  pkg/golinters/forbidigo.go
  pkg/golinters/funlen.go
  pkg/golinters/goanalysis/runner.go
  pkg/golinters/goanalysis/runners.go
  pkg/golinters/gocognit.go
  pkg/golinters/goconst.go
  pkg/golinters/gocyclo.go
  pkg/golinters/godox.go
  pkg/golinters/gofmt_common.go
  pkg/golinters/importas.go
  pkg/golinters/lll.go
  pkg/golinters/makezero.go
  pkg/golinters/nestif.go
  pkg/golinters/nolintlint.go
  pkg/golinters/nolintlint/nolintlint.go
  pkg/golinters/nolintlint/nolintlint_test.go
  pkg/golinters/prealloc.go
  pkg/golinters/unconvert.go
  pkg/logutils/stderr_log.go
  pkg/packages/util_test.go
  pkg/printers/checkstyle_test.go
  pkg/printers/codeclimate_test.go
  pkg/printers/github_test.go
  pkg/printers/html_test.go
  pkg/printers/json_test.go
  pkg/printers/junitxml_test.go
  pkg/printers/tab_test.go
  pkg/printers/text_test.go
  pkg/result/issue.go
  pkg/result/processors/base_rule.go
  pkg/result/processors/exclude_rules_test.go
  pkg/result/processors/fixer.go
  pkg/result/processors/identifier_marker_test.go
  pkg/result/processors/sort_results_test.go
  scripts/website/expand_templates/main.go
  test/output_test.go
  test/testshared/directives.go
  test/testshared/runner.go
Labels: topic: cleanup

#4527 feat: add verify command
  .github/workflows/pr.yml
  .golangci.yml
  Makefile
  go.mod
  go.sum
  pkg/commands/config.go
  pkg/commands/config_verify.go
  pkg/commands/config_verify_test.go
  pkg/commands/root.go
  scripts/website/copy_jsonschema/main.go
  scripts/website/expand_templates/main.go
  scripts/website/github/github.go
Labels: enhancement, area: CLI, area: JSON schema

#4542 dev: silence help on some commands usage on error
  pkg/commands/custom.go
  pkg/commands/linters.go
  pkg/commands/run.go
Labels: enhancement, topic: cosmetic

#4545 docs: update documentation assets
  .github/workflows/post-release.yml
  .golangci.reference.yml
  .golangci.yml
  .goreleaser.yml
  CHANGELOG.md
  assets/cli-help.json
  assets/linters-info.json
  jsonschema/golangci.jsonschema.json
Labels: area: docs

#4546 docs: update documentation
  README.md
Labels: area: docs

#4547 docs: fix default value for sloglint no-global
  .golangci.next.reference.yml
  .golangci.reference.yml
  jsonschema/golangci.jsonschema.json
  jsonschema/golangci.next.jsonschema.json
Labels: bug, area: docs, area: config, linter: update, area: JSON schema

#4552 fix: filter invalid issues before other processors
  pkg/lint/runner.go
  pkg/logutils/logutils.go
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/autogenerated_exclude_test.go
  pkg/result/processors/invalid_issue.go
  pkg/result/processors/invalid_issue_test.go
  pkg/result/processors/nolint.go
Labels: bug, area: processors

#4566 docs: remove invalid example about mixing files and directory
  docs/src/docs/welcome/quick-start.mdx
Labels: bug, area: docs

#4571 docs: improve linters page
  docs/src/docs/usage/linters.mdx
  scripts/website/expand_templates/linters.go
Labels: enhancement, area: docs

#4568 fix: display warnings on deprecated linter options
  .golangci.yml
  pkg/config/linters_settings.go
  pkg/config/loader.go
  pkg/config/run.go
  pkg/golinters/godot.go
Labels: bug, area: config

#4573 fix: the TeamCity inspectionType service message
  pkg/printers/teamcity.go
  pkg/printers/teamcity_test.go
Labels: bug, area: output

#4574 fix: missing output format
  pkg/config/output.go
Labels: bug, area: output

#4576 dev: remove unused markdownlint config file
  .markdownlint.yaml
Labels: topic: cleanup

#4577 dev: minor clean up
  assets/linters-info.json
  pkg/golinters/bidichk.go
  pkg/golinters/bodyclose.go
  pkg/golinters/errchkjson.go
  pkg/golinters/grouper.go
  pkg/lint/lintersdb/builder_linter.go
  test/testdata/configs/decorder_custom.yml
  test/testdata/configs/errcheck_exclude_functions.yml
  test/testdata/configs/errcheck_ignore_config.yml
  test/testdata/configs/goheader-fix.yml
  test/testdata/configs/goheader.yml
  test/testdata/configs/ireturn_allow.yml
  test/testdata/configs/nonamedreturns_custom.yml
  test/testdata/configs/paralleltest_custom.yml
  test/testdata/configs/predeclared_custom.yml
  test/testdata/decorder.go
  test/testdata/decorder_custom.go
  test/testdata/decorder_default.go
  test/testdata/errcheck_exclude_functions.go
  test/testdata/errcheck_ignore.go
  test/testdata/fix/in/goheader_1.go
  test/testdata/fix/in/goheader_2.go
  test/testdata/fix/in/goheader_3.go
  test/testdata/fix/out/goheader_1.go
  test/testdata/fix/out/goheader_2.go
  test/testdata/fix/out/goheader_3.go
  test/testdata/goheader_bad.go
  test/testdata/goheader_good.go
  test/testdata/ireturn.go
  test/testdata/ireturn_allow.go
  test/testdata/lll_import_multi.go
  test/testdata/lll_import_single.go
  test/testdata/nonamedreturns_custom.go
  test/testdata/paralleltest_custom.go
  test/testdata/predeclared_custom.go
  test/testdata/spancheck/configs/spancheck_enable_all.yml
  test/testdata/spancheck/spancheck_enable_all.go
  test/testdata/tenv_fuzz.go
  test/testdata/testifylint_bool_compare_only.go
  test/testdata/testifylint_require_error_only.go
  test/testdata/thelper_fuzz.go
Labels: topic: cleanup

#4587 fix: hide useless warning
  .golangci.yml
  pkg/commands/linters.go
Labels: bug, area: CLI

#4588 docs: update documentation assets
  CHANGELOG.md
Labels: area: docs

#4557 dev: clean code arround CLI args usage
  pkg/commands/config.go
  pkg/commands/linters.go
  pkg/commands/run.go
  pkg/config/loader.go
  pkg/lint/package.go
  pkg/lint/package_test.go
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/invalid_issue.go
  pkg/result/processors/skip_dirs.go
  pkg/result/processors/skip_dirs_test.go
Labels: enhancement, topic: cleanup

#4562 feat: deprecate usage of linter alternative names
  pkg/golinters/internal/diff_test.go
  pkg/lint/lintersdb/validator.go
  pkg/lint/lintersdb/validator_test.go
  pkg/logutils/mock.go
Labels: enhancement, area: config, linter: update

#4585 dev: add test for grouper linter
  test/testdata/configs/grouper.yml
  test/testdata/grouper.go
Labels: area: tests

#4567 feat: err113 analyzer name
  .golangci.next.reference.yml
  jsonschema/golangci.next.jsonschema.json
  pkg/golinters/err113.go
  pkg/lint/lintersdb/builder_linter.go
  pkg/printers/testdata/golden-json.json
  pkg/printers/testdata/in-report-data.json
  test/testdata/err113.go
  test/testdata/goerr113.go
Labels: enhancement, linter: update

#4572 feat: replace gomnd by mnd
  .golangci.next.reference.yml
  .golangci.yml
  docs/src/docs/usage/false-positives.mdx
  jsonschema/golangci.next.jsonschema.json
  pkg/commands/run.go
  pkg/config/linters_settings.go
  pkg/golinters/gomnd.go
  pkg/golinters/mnd.go
  pkg/lint/lintersdb/builder_linter.go
  pkg/printers/testdata/golden-json.json
  pkg/printers/testdata/in-report-data.json
  test/testdata/mnd.go
Labels: enhancement, linter: update

#4590 docs: update documentation
  README.md
Labels: area: docs

#4594 dev: add fix test for tagalign linter
  test/testdata/fix/in/tagalign.go
  test/testdata/fix/out/tagalign.go
Labels: area: tests

#4595 dev: enable testifylint linter
  .golangci.yml
  pkg/golinters/misspell_test.go
  pkg/result/processors/autogenerated_exclude_test.go
  pkg/result/processors/skip_files_test.go
Labels: topic: cleanup

#4592 dev: unifying processors code style
  pkg/lint/runner.go
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/cgo.go
  pkg/result/processors/diff.go
  pkg/result/processors/exclude.go
  pkg/result/processors/exclude_rules.go
  pkg/result/processors/filename_unadjuster.go
  pkg/result/processors/fixer.go
  pkg/result/processors/identifier_marker.go
  pkg/result/processors/invalid_issue.go
  pkg/result/processors/max_from_linter.go
  pkg/result/processors/max_per_file_from_linter.go
  pkg/result/processors/max_same_issues.go
  pkg/result/processors/nolint.go
  pkg/result/processors/path_prefixer.go
  pkg/result/processors/path_prettifier.go
  pkg/result/processors/path_shortener.go
  pkg/result/processors/severity.go
  pkg/result/processors/skip_dirs.go
  pkg/result/processors/skip_files.go
  pkg/result/processors/sort_results.go
  pkg/result/processors/source_code.go
  pkg/result/processors/uniq_by_line.go
Labels: topic: cosmetic

#4598 dev: add fix test for mirror linter
  test/testdata/fix/in/mirror.go
  test/testdata/fix/out/mirror.go
Labels: area: tests

#4599 dev: clean up unused receivers with revive
  .golangci.yml
  pkg/commands/cache.go
  pkg/goanalysis/linter.go
  pkg/goanalysis/metalinter.go
  pkg/lint/lintersdb/builder_linter.go
  pkg/lint/lintersdb/validator.go
  pkg/lint/package.go
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/path_prettifier.go
Labels: topic: cosmetic

#4602 Add `pre-commit` hook to run `config verify`
  .pre-commit-hooks.yaml
Labels: enhancement, area: pre-commit
