Repository golangci/golangci-lint, pull requests merged in 2024-12, with the labels that each got.

#5179 fix: improve Go version detection inside workspace
  go.mod
  pkg/config/config.go
  pkg/golinters/gomodguard/testdata/go.mod
  pkg/golinters/gomodguard/testdata/go.sum
  pkg/golinters/gomodguard/testdata/gomodguard.yml
Labels: bug, area: workspace

#5194 dev: refactor ifs with cmp.Or
  cmd/golangci-lint/main.go
  pkg/config/config.go
  pkg/config/loader.go
  pkg/golinters/errcheck/errcheck.go
  pkg/golinters/godot/godot.go
  pkg/golinters/revive/revive.go
  pkg/result/processors/severity.go
Labels: topic: cosmetic

#5193 dev: remove useless call to WithLoadForGoAnalysis
  pkg/golinters/cyclop/cyclop.go
  pkg/lint/lintersdb/builder_linter.go
Labels: topic: cleanup

#5200 docs: Ignore previously ignored contributors
  README.md
Labels: enhancement, area: docs

#5202 docs: Make contributors URL shorter
  README.md
Labels: area: docs, topic: cleanup

#5201 dev: sync checker with x/tools@v0.28.0
  .golangci.next.reference.yml
  .golangci.yml
  internal/x/LICENSE
  internal/x/tools/analysisflags/readme.md
  internal/x/tools/analysisflags/url.go
  internal/x/tools/analysisinternal/analysis.go
  internal/x/tools/analysisinternal/readme.md
  jsonschema/golangci.next.jsonschema.json
  pkg/goanalysis/runner.go
  pkg/goanalysis/runner_action.go
  pkg/goanalysis/runner_action_cache.go
  pkg/goanalysis/runner_checker.go
  pkg/goanalysis/runner_loadingpackage.go
Labels: enhancement, area: core

#5205 dev: format linter descriptions inside help command
  pkg/commands/help.go
Labels: topic: cosmetic

#5206 dev: simplify cutVal implementation
  pkg/printers/teamcity.go
Labels: topic: cosmetic

#5207 dev: enhance help linters output on fast and auto-fix capabilities
  pkg/commands/help.go
Labels: topic: cosmetic

#5209 feat: display linters help as JSON
  pkg/commands/help.go
Labels: enhancement, area: CLI

#5211 dev: remove archived mitchellh/go-ps
  go.mod
  go.sum
  test/bench/bench_test.go
Labels: topic: cleanup

#5216 docs: update contributors image
  docs/src/docs/index.mdx
Labels: area: docs, topic: cosmetic

#5226 docs: empty alias with importas
  .golangci.next.reference.yml
Labels: enhancement, area: docs

#5228 gosec: handling of global nosec option when it is false
  pkg/golinters/gosec/gosec.go
  pkg/golinters/gosec/gosec_test.go
  pkg/golinters/gosec/testdata/gosec_nosec.go
  pkg/golinters/gosec/testdata/gosec_nosec.yml
Labels: bug, linter: update

#5234 docs: remove outdated update contributors instructions
  Makefile
  docs/src/docs/contributing/workflow.mdx
  docs/src/docs/index.mdx
Labels: area: docs, topic: cosmetic

#5238 goheader: fix invalid position
  pkg/golinters/goheader/goheader.go
  pkg/golinters/goheader/testdata/fix/in/goheader_4.go
  pkg/golinters/goheader/testdata/fix/out/goheader_4.go
  pkg/result/processors/fixer.go
Labels: bug, linter: update

#5239 docs: update completion guide
  docs/src/docs/welcome/integrations.mdx
Labels: area: docs

#5242 fix: remove decoder, sloglint, tagalin from 'format' preset
  pkg/lint/lintersdb/builder_linter.go
Labels: topic: cleanup, linter: update

#5241 dev: publish AUR from sources
  .goreleaser.yml
Labels: enhancement, area: install, area: ci

#5243 feat: improve formatter messages
  pkg/golinters/gci/internal/analyzer.go
  pkg/golinters/gci/testdata/gci.go
  pkg/golinters/gci/testdata/gci_cgo.go
  pkg/golinters/gofmt/gofmt.go
  pkg/golinters/gofmt/testdata/gofmt.go
  pkg/golinters/gofmt/testdata/gofmt_cgo.go
  pkg/golinters/gofmt/testdata/gofmt_no_simplify.go
  pkg/golinters/gofmt/testdata/gofmt_rewrite_rules.go
  pkg/golinters/gofumpt/gofumpt.go
  pkg/golinters/gofumpt/testdata/gofumpt.go
  pkg/golinters/gofumpt/testdata/gofumpt_cgo.go
  pkg/golinters/gofumpt/testdata/gofumpt_with_extra.go
  pkg/golinters/goimports/goimports.go
  pkg/golinters/goimports/testdata/goimports.go
  pkg/golinters/goimports/testdata/goimports_cgo.go
  pkg/golinters/goimports/testdata/goimports_local.go
  pkg/golinters/internal/diff.go
  test/run_test.go
Labels: linter: update

#5250 feat: disable timeout if timeout <= 0
  .golangci.next.reference.yml
  pkg/commands/flagsets.go
  pkg/commands/run.go
Labels: enhancement, area: config

#5251 dev: improve --presets and --out-format flags help
  pkg/commands/flagsets.go
Labels: topic: cosmetic, area: CLI

#5253 fix: move uniq-by-line field from output to issues
  .golangci.next.reference.yml
  jsonschema/golangci.next.jsonschema.json
  pkg/commands/flagsets.go
  pkg/config/issues.go
  pkg/config/loader.go
  pkg/config/output.go
  pkg/result/processors/uniq_by_line.go
  pkg/result/processors/uniq_by_line_test.go
Labels: area: config, topic: cleanup

#5254 dev: use bool pointer on deprecated bool options
  pkg/commands/flagsets.go
  pkg/config/issues.go
  pkg/config/linters_settings.go
  pkg/config/loader.go
  pkg/config/run.go
  pkg/golinters/godot/godot.go
  pkg/golinters/govet/govet.go
  pkg/golinters/usestdlibvars/usestdlibvars.go
Labels: area: config, topic: cleanup

#5240 Add nilnesserr linter
  .golangci.next.reference.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/golinters/nilnesserr/nilnesserr.go
  pkg/golinters/nilnesserr/nilnesserr_integration_test.go
  pkg/golinters/nilnesserr/testdata/nilnesserr.go
  pkg/golinters/nilnesserr/testdata/nilnesserr_cgo.go
  pkg/lint/lintersdb/builder_linter.go
Labels: linter: new

#5245 fix: enable paths with junction inside windows
  pkg/fsutils/fsutils.go
  pkg/fsutils/fsutils_unix.go
  pkg/fsutils/fsutils_windows.go
Labels: bug, platform: windows

#5246 feat: apply formatters after the suggested fixes
  go.mod
  go.sum
  pkg/config/config.go
  pkg/goformatters/formatters.go
  pkg/goformatters/gci/gci.go
  pkg/goformatters/gofmt/gofmt.go
  pkg/goformatters/gofumpt/gofumpt.go
  pkg/goformatters/goimports/goimports.go
  pkg/lint/runner.go
  pkg/result/processors/fixer.go
  pkg/result/processors/formatter.go
Labels: enhancement, area: auto-fix

#5260 docs: update "Contributing FAQ"
  docs/src/docs/contributing/faq.mdx
Labels: area: docs, topic: cleanup

#5265 dev: clarifies and homogenizes formatter descriptions
  pkg/golinters/gci/internal/analyzer.go
  pkg/golinters/gofmt/gofmt.go
  pkg/golinters/gofumpt/gofumpt.go
  pkg/golinters/goimports/goimports.go
Labels: area: docs, topic: cosmetic

#5259 Add exptostd linter
  .golangci.next.reference.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/golinters/exptostd/exptostd.go
  pkg/golinters/exptostd/exptostd_integration_test.go
  pkg/golinters/exptostd/testdata/exptostd.go
  pkg/golinters/exptostd/testdata/exptostd_cgo.go
  pkg/golinters/exptostd/testdata/exptostd_go123.go
  pkg/golinters/exptostd/testdata/exptostd_go123_cgo.go
  pkg/golinters/exptostd/testdata/fix/in/exptostd.go
  pkg/golinters/exptostd/testdata/fix/out/exptostd.go
  pkg/golinters/exptostd/testdata/go.mod
  pkg/golinters/exptostd/testdata/go.sum
  pkg/lint/lintersdb/builder_linter.go
Labels: linter: new
