Repository golangci/golangci-lint, pull requests merged in 2024-11, with the labels that each got.

#5098 dev: updates internal code borrowed from Go
  .golangci.yml
  go.mod
  go.sum
  internal/cache/LICENSE
  internal/cache/cache.go
  internal/cache/cache_gcil.go
  internal/cache/cache_test.go
  internal/cache/default.go
  internal/cache/default_gcil.go
  internal/cache/hash.go
  internal/cache/hash_gcil.go
  internal/cache/prog.go
  internal/cache/readme.md
  internal/mmap/LICENSE
  internal/mmap/mmap.go
  internal/mmap/mmap_other.go
  internal/mmap/mmap_unix.go
  internal/mmap/mmap_windows.go
  internal/mmap/readme.md
  internal/pkgcache/pkgcache.go
  internal/quoted/LICENSE
  internal/quoted/quoted.go
  internal/quoted/quoted_test.go
  internal/quoted/readme.md
  internal/renameio/readme.md
  internal/renameio/renameio.go
  internal/renameio/renameio_test.go
  internal/renameio/umask_test.go
  internal/robustio/LICENSE
  internal/testenv/LICENSE
  internal/testenv/readme.md
  internal/testenv/testenv.go
  internal/testenv/testenv_notunix.go
  internal/testenv/testenv_notwin.go
  internal/testenv/testenv_unix.go
  internal/testenv/testenv_windows.go
  pkg/commands/cache.go
  pkg/goanalysis/runner.go
  pkg/goanalysis/runners.go
  scripts/website/expand_templates/main.go
Labels: enhancement, area: cache

#5100 dev: isolates the code borrowed from Go
  .golangci.yml
  internal/cache/cache.go
  internal/go/LICENSE
  internal/go/cache/cache.go
  internal/go/cache/cache_gcil.go
  internal/go/cache/cache_test.go
  internal/go/cache/default.go
  internal/go/cache/default_gcil.go
  internal/go/cache/hash.go
  internal/go/cache/hash_gcil.go
  internal/go/cache/hash_test.go
  internal/go/cache/prog.go
  internal/go/cache/readme.md
  internal/go/mmap/mmap.go
  internal/go/mmap/mmap_other.go
  internal/go/mmap/mmap_unix.go
  internal/go/mmap/mmap_windows.go
  internal/go/mmap/readme.md
  internal/go/quoted/quoted.go
  internal/go/quoted/quoted_test.go
  internal/go/quoted/readme.md
  internal/go/robustio/readme.md
  internal/go/robustio/robustio.go
  internal/go/robustio/robustio_darwin.go
  internal/go/robustio/robustio_flaky.go
  internal/go/robustio/robustio_other.go
  internal/go/robustio/robustio_windows.go
  internal/go/testenv/readme.md
  internal/go/testenv/testenv.go
  internal/go/testenv/testenv_notunix.go
  internal/go/testenv/testenv_notwin.go
  internal/go/testenv/testenv_unix.go
  internal/go/testenv/testenv_windows.go
  internal/mmap/LICENSE
  internal/mmap/readme.md
  internal/pkgcache/pkgcache.go
  internal/quoted/LICENSE
  internal/quoted/readme.md
  internal/robustio/LICENSE
  internal/testenv/LICENSE
  internal/testenv/readme.md
  pkg/commands/cache.go
  pkg/commands/run.go
  pkg/goanalysis/runner.go
  pkg/goanalysis/runner_action.go
  pkg/goanalysis/runners.go
  pkg/lint/context.go
  pkg/lint/linter/context.go
  pkg/result/processors/fixer.go
Labels: topic: cosmetic, area: cache

#5101 Improve readability and maintenance of `internal/cache`
  internal/cache/cache.go
  internal/cache/cache_test.go
  internal/cache/testdata/hello.go
  pkg/timeutils/stopwatch.go
Labels: topic: cleanup, area: cache

#5102 dev: extends usage of new Stopwatch methods
  pkg/goanalysis/runner_action.go
  pkg/lint/runner.go
  pkg/result/processors/fixer.go
Labels: topic: cosmetic

#5104 docs: fix iface linter name
  .golangci.next.reference.yml
Labels: area: docs

#5107 docs: replace staticcheck.io with staticcheck.dev
  .golangci.next.reference.yml
  .golangci.reference.yml
  assets/linters-info.json
  pkg/lint/lintersdb/builder_linter.go
Labels: area: docs

#5106 dev: use secure links
  docs/.gitignore
  pkg/golinters/mnd/testdata/mnd.go
Labels: topic: cosmetic

#5112 fix: improve Go detection
  pkg/config/config.go
Labels: bug

#5110 feat: deprecation step 2 of execinquery and gomnd
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/config/linters_settings.go
  pkg/config/loader.go
  pkg/golinters/execinquery/execinquery.go
  pkg/golinters/execinquery/execinquery_integration_test.go
  pkg/golinters/execinquery/testdata/execinquery.go
  pkg/golinters/mnd/mnd.go
  pkg/lint/lintersdb/builder_linter.go
Labels: enhancement, linter: update

#5109 fix: Go version propagation
  pkg/config/loader.go
  pkg/goanalysis/runner.go
  pkg/goanalysis/runner_action.go
  pkg/goanalysis/runner_action_cache.go
  pkg/goanalysis/runner_base.go
  pkg/goanalysis/runner_facts.go
  pkg/goanalysis/runner_loadingpackage.go
  pkg/goanalysis/runners.go
  pkg/goanalysis/runners_cache.go
  pkg/lint/linter/config.go
Labels: bug, area: core

#5116 docs: improve forbidigo pattern examples for built-in functions
  .golangci.next.reference.yml
  .golangci.reference.yml
  jsonschema/golangci.jsonschema.json
  jsonschema/golangci.next.jsonschema.json
Labels: enhancement, area: docs

#5123 docs: update GitHub Action assets
  assets/github-action-config.json
Labels: github_actions

#5124 docs: update documentation
  README.md
Labels: area: docs

#5125 docs: fix links to gocritic checks
  .golangci.next.reference.yml
  .golangci.reference.yml
Labels: bug, area: docs

#5126 docs: missing doc link for sloglint.args-on-sep-lines
  .golangci.next.reference.yml
  .golangci.reference.yml
Labels: bug, area: docs

#5129 fix: ignore cache error when file not found
  internal/go/cache/cache.go
Labels: bug, area: cache

#5131 docs: improve testifylint description of require-f-funcs flag
  .golangci.next.reference.yml
  .golangci.reference.yml
  jsonschema/golangci.jsonschema.json
  jsonschema/golangci.next.jsonschema.json
Labels: enhancement, area: docs

#5140 docs: fix URL for revive.ignore-generated-header
  .golangci.next.reference.yml
  .golangci.reference.yml
Labels: area: docs

#5139 docs: remove golint on 'performance' page
  docs/src/docs/product/performance.mdx
Labels: area: docs, topic: cleanup

#5146 dev: publish AUR -bin automatically
  .goreleaser.yml
Labels: enhancement, area: install, area: ci

#5148 docs: Simplify team and contributors section
  .github/contributors/.gitignore
  .github/contributors/.prettierrc.json
  .github/contributors/def.d.ts
  .github/contributors/generate.ts
  .github/contributors/info.ts
  .github/contributors/package-lock.json
  .github/contributors/package.json
  .github/contributors/rewrite_readme.ts
  .github/contributors/tsconfig.json
  .github/workflows/post-release.yml
  README.md
Labels: enhancement, area: docs, area: ci

#5151 dev: add missing AUR_KEY secret
  .github/workflows/tag.yml
Labels: bug, area: install, area: ci

#5130 dev: publish snap
  .github/workflows/tag.yml
  .goreleaser.yml
Labels: enhancement, area: install, area: ci

#5156 dev: fix release workflow
  .github/workflows/tag.yml
Labels: bug, area: install, area: ci

#5158 dev: fix AUR prepare step
  .goreleaser.yml
Labels: bug, area: install, area: ci

#5077 build(deps): bump github.com/timakin/bodyclose from 574207250966 to ed6a65f985e
  go.mod
  go.sum
  pkg/golinters/bodyclose/bodyclose.go
Labels: dependencies, linter: update version, go

#5160 govet: add `stdversion` analyzer
  .golangci.next.reference.yml
  jsonschema/golangci.next.jsonschema.json
  pkg/golinters/govet/govet.go
Labels: linter: update

#5166 docs: fix GitLab doc link in CodeClimateIssue comment
  pkg/printers/codeclimate.go
Labels: area: docs, topic: cleanup

#5167 build(deps): bump github.com/shirou/gopsutil to v4.24.10
  go.mod
  go.sum
  test/bench/bench_test.go
Labels: dependencies, go

#5169 docs: revert unwanted JSONSchema/doc changes
  .golangci.reference.yml
  jsonschema/golangci.jsonschema.json
Labels: bug, area: docs

#5171 build(deps): bump santhosh-tekuri/jsonschema/v5 to v6
  go.mod
  go.sum
  pkg/commands/config_verify.go
  test/configuration_file_test.go
Labels: dependencies, go, area: JSON schema

#5173 dev: refactor linter constructors for consistency
  pkg/golinters/asasalint/asasalint.go
  pkg/golinters/bidichk/bidichk.go
  pkg/golinters/dupword/dupword.go
  pkg/golinters/errchkjson/errchkjson.go
  pkg/golinters/errorlint/errorlint.go
  pkg/golinters/gosmopolitan/gosmopolitan.go
  pkg/golinters/grouper/grouper.go
  pkg/golinters/maintidx/maintidx.go
  pkg/golinters/musttag/musttag.go
  pkg/golinters/nilnil/nilnil.go
  pkg/golinters/testpackage/testpackage.go
  pkg/golinters/thelper/thelper.go
  pkg/golinters/usestdlibvars/usestdlibvars.go
Labels: topic: cosmetic
