Repository golangci/golangci-lint, pull requests merged in 2024-04, with the labels that each got.

#4583 feat: add fatcontext linter
  .golangci.next.reference.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/golinters/fatcontext.go
  pkg/lint/lintersdb/builder_linter.go
  test/testdata/fatcontext.go
Labels: enhancement, linter: new

#4591 dev: option to not check deprecation
  .golangci.yml
  pkg/commands/config.go
  pkg/commands/linters.go
  pkg/commands/run.go
  pkg/config/config.go
  pkg/config/loader.go
  pkg/lint/lintersdb/validator.go
Labels: topic: cleanup

#4605 dev: set timeout for loading JSON schema
  pkg/commands/config_verify.go
Labels: area: CLI, area: JSON schema

#4607 docs: fix links to Module and Go Plugins
  docs/src/docs/contributing/new-linters.mdx
Labels: bug, area: docs, blocked

#4617 fix: JSON schema about severities
  jsonschema/golangci.jsonschema.json
  jsonschema/golangci.next.jsonschema.json
Labels: bug, area: JSON schema

#4615 chore: add chocolatey
  .github/workflows/tag.yml
  .goreleaser.yml
  docs/src/docs/welcome/install.mdx
Labels: enhancement, area: ci

#4628 docs: remove deprecated Atom from Editor Integrations
  docs/src/docs/index.mdx
  docs/src/docs/welcome/integrations.mdx
Labels: area: docs, topic: cleanup

#4631 dev: group skip-dir related elements
  pkg/commands/flagsets.go
  pkg/lint/runner.go
  pkg/packages/exclude.go
  pkg/packages/exclude_test.go
  pkg/result/processors/skip_dirs.go
  pkg/result/processors/skip_dirs_test.go
Labels: topic: cleanup

#4637 docs: use proper templates when creating GitHub issues
  docs/src/docs/welcome/faq.mdx
Labels: enhancement, area: docs

#4636 dev: improve formatting and description in flagsets
  pkg/commands/flagsets.go
Labels: topic: cosmetic, area: CLI

#4638 dev: clean DefaultExcludePatterns and improve CLI render
  pkg/commands/flagsets.go
  pkg/config/issues.go
Labels: area: docs, topic: cleanup, topic: cosmetic, area: CLI

#4641 dev: remove alternatives names from CLI help
  pkg/commands/help.go
Labels: topic: cosmetic, area: CLI

#4642 dev: sorts deprecated linters at the end of lists
  pkg/commands/help.go
  scripts/website/expand_templates/linters.go
  scripts/website/types/types.go
Labels: area: docs, topic: cosmetic, area: CLI

#4640 fix: keep only typecheck issues
  pkg/result/processors/invalid_issue.go
  pkg/result/processors/invalid_issue_test.go
Labels: bug, area: processors

#4649 dev: close errcheck exclude file
  pkg/golinters/errcheck/errcheck.go
Labels: topic: cleanup

#4650 dev: eliminate redundant indentation
  .golangci.yml
  pkg/lint/lintersdb/builder_plugin_go.go
Labels: topic: cleanup

#4647 dev: replace fmt.Errorf by errors.New
  pkg/commands/config_verify.go
Labels: topic: cleanup

#4652 execinquery: deprecation
  pkg/lint/lintersdb/builder_linter.go
Labels: enhancement, linter: update

#4656 dev: fix broken links to the website
  .github/ISSUE_TEMPLATE/bug_report.yml
  pkg/lint/lintersdb/builder_plugin_go.go
Labels: bug, area: docs

#4655 fix: use plugin version
  pkg/commands/internal/builder.go
Labels: bug, linter: custom

#4657 dev: fix shellcheck lint issues
  install.sh
Labels: topic: cleanup

#4660 dev: improve goreleaser configuration
  .goreleaser.yml
Labels: topic: cleanup

#4653 fix: speed up "fast" linters
  pkg/golinters/typecheck.go
  pkg/lint/lintersdb/builder_linter.go
  pkg/lint/lintersdb/manager.go
  pkg/lint/lintersdb/manager_test.go
  test/enabled_linters_test.go
Labels: bug, topic: speed, linter: update

#4645 build(deps): bump go-simpler.org/sloglint from 0.5.1 to 0.6.0
  .golangci.next.reference.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/config/linters_settings.go
  pkg/config/loader.go
  pkg/golinters/sloglint/sloglint.go
  pkg/golinters/sloglint/testdata/sloglint_context_only.go
  pkg/golinters/sloglint/testdata/sloglint_context_only.yml
Labels: dependencies, linter: update version, go

#4663 fix: skip go.mod report inside autogenerated_exclude processor
  pkg/result/processors/autogenerated_exclude.go
Labels: bug, area: processors

#4675 dev: dedicated package about IllTypedError parsing
  pkg/goanalysis/pkgerrors/errors.go
  pkg/goanalysis/pkgerrors/extract.go
  pkg/goanalysis/pkgerrors/extract_test.go
  pkg/goanalysis/pkgerrors/parse.go
  pkg/goanalysis/pkgerrors/parse_test.go
  pkg/goanalysis/runner_action.go
  pkg/goanalysis/runners.go
Labels: topic: cleanup

#4674 fix: don't hide typecheck errors inside diff processor
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/diff.go
  pkg/result/processors/invalid_issue.go
  pkg/result/processors/processor.go
Labels: bug, area: processors

#4672 Add new linter canonicalheader
  .golangci.next.reference.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/golinters/canonicalheader/canonicalheader.go
  pkg/golinters/canonicalheader/canonicalheader_test.go
  pkg/golinters/canonicalheader/testdata/canonicalheader.go
  pkg/lint/lintersdb/builder_linter.go
Labels: enhancement, linter: new

#4676 dev: removes BaseRule, ExcludeRule, SeverityRule duplications
  pkg/lint/runner.go
  pkg/result/processors/base_rule.go
  pkg/result/processors/exclude.go
  pkg/result/processors/exclude_rules.go
  pkg/result/processors/exclude_rules_test.go
  pkg/result/processors/exclude_test.go
  pkg/result/processors/severity.go
  pkg/result/processors/severity_test.go
Labels: topic: cleanup

#4673 dev: clean deprecated options
  .golangci.next.reference.yml
  jsonschema/golangci.next.jsonschema.json
  pkg/config/linters_settings.go
  pkg/config/loader.go
  pkg/golinters/errcheck/testdata/errcheck_exclude.go
  pkg/golinters/errcheck/testdata/errcheck_exclude.txt
  pkg/golinters/errcheck/testdata/errcheck_exclude.yml
  pkg/golinters/errcheck/testdata/errcheck_ignore.go
  pkg/golinters/errcheck/testdata/errcheck_ignore_config.yml
Labels: area: docs, area: config, topic: cleanup

#4681 feat: log an error when using previously deprecated linters
  pkg/lint/linter/config.go
  pkg/lint/linter/linter.go
  pkg/lint/lintersdb/builder_linter.go
  pkg/lint/lintersdb/manager.go
  scripts/website/dump_info/main.go
  scripts/website/expand_templates/thanks.go
  test/enabled_linters_test.go
Labels: enhancement, topic: cleanup
