Repository golangci/golangci-lint, pull requests merged in 2024-07, with the labels that each got.

#4843 docs: add link on linter without configuration
  docs/src/docs/contributing/workflow.mdx
  docs/src/docs/usage/linters.mdx
  scripts/website/expand_templates/linters.go
Labels: enhancement, area: docs

#4857 docs: remove 'trusted by' page
  docs/src/config/sidebar.yml
  docs/src/docs/product/trusted-by.mdx
Labels: enhancement, area: docs

#4855 dev: add action to add checklist for new linter
  .github/new-linter-checklist.md
  .github/workflows/new-linter-checklist.yaml
Labels: enhancement, area: ci

#4860 chore: change .yaml to .yml for consistency
  .github/workflows/codeql.yml
  .github/workflows/new-linter-checklist.yml
Labels: topic: cleanup

#4861 docs: improve grammar of new linter checklist
  .github/new-linter-checklist.md
Labels: area: docs, topic: cleanup

#4870 fix: typecheck issues should never be ignored
  pkg/result/processors/autogenerated_exclude.go
  pkg/result/processors/autogenerated_exclude_test.go
  pkg/result/processors/invalid_issue.go
  pkg/result/processors/issues.go
  pkg/result/processors/max_from_linter.go
  pkg/result/processors/max_per_file_from_linter.go
  pkg/result/processors/max_same_issues.go
  pkg/result/processors/uniq_by_line.go
Labels: bug, area: processors

#4881 docs: improve ireturn documentation
  .golangci.next.reference.yml
  .golangci.reference.yml
Labels: area: docs, area: config

#4882 feat: improve processors filtering stats
  pkg/lint/runner.go
Labels: enhancement, area: processors

#4884 dev: add comment to clarify using empty issues slice
  pkg/lint/runner.go
Labels: topic: cosmetic

#4890 unused: remove exported-is-used option
  jsonschema/golangci.next.jsonschema.json
  pkg/config/linters_settings.go
  pkg/config/loader.go
  pkg/golinters/unused/unused.go
Labels: bug, linter: update
