Repository golangci/golangci-lint, pull requests merged in 2024-08, with the labels that each got.

#4836 go1.23 support
  .github/workflows/documentation.yml
  .github/workflows/post-release.yml
  .github/workflows/pr-documentation.yml
  .github/workflows/pr-extra.yml
  .github/workflows/pr.yml
  .github/workflows/tag.yml
  .goreleaser.yml
  build/buildx-alpine.Dockerfile
  build/buildx.Dockerfile
  go.mod
  go.sum
  pkg/golinters/govet/govet.go
  pkg/golinters/govet/govet_test.go
  test/run_test.go
  test/testshared/integration/run.go
Labels: enhancement

#4902 docs: update GitHub Action assets
  assets/github-action-config.json
Labels: github_actions

#4903 docs: update documentation
  README.md
Labels: area: docs

#4906 gosec: add G602 analyzer
  .golangci.next.reference.yml
  .golangci.reference.yml
  jsonschema/golangci.jsonschema.json
  jsonschema/golangci.next.jsonschema.json
  pkg/golinters/gosec/gosec.go
Labels: bug, linter: update

#4907 staticcheck: propagate Go version
  pkg/goanalysis/runner_loadingpackage.go
  pkg/golinters/gosimple/gosimple.go
  pkg/golinters/internal/staticcheck_common.go
  pkg/golinters/spancheck/testdata/go.mod
  pkg/golinters/staticcheck/staticcheck.go
  pkg/golinters/stylecheck/stylecheck.go
  pkg/golinters/unused/unused.go
  pkg/lint/lintersdb/builder_linter.go
Labels: bug, linter: update

#4923 chore: update gofmt
  go.mod
  go.sum
Labels: dependencies, linter: update version, go

#4916 exportloopref: deprecation
  .golangci.yml
  pkg/commands/config_verify.go
  pkg/commands/config_verify_test.go
  pkg/commands/internal/builder_test.go
  pkg/commands/internal/configuration_test.go
  pkg/config/config_test.go
  pkg/config/issues_test.go
  pkg/config/linters_settings_test.go
  pkg/config/linters_test.go
  pkg/config/output_test.go
  pkg/config/run_test.go
  pkg/config/severity_test.go
  pkg/goanalysis/pkgerrors/errors.go
  pkg/goanalysis/pkgerrors/extract_test.go
  pkg/goanalysis/runner_loadingpackage.go
  pkg/goanalysis/runners.go
  pkg/golinters/gocritic/gocritic_test.go
  pkg/golinters/gosec/gosec_test.go
  pkg/golinters/internal/diff.go
  pkg/golinters/misspell/misspell_test.go
  pkg/golinters/nolintlint/internal/nolintlint_test.go
  pkg/golinters/thelper/testdata/thelper.go
  pkg/lint/lintersdb/builder_linter.go
  pkg/lint/lintersdb/builder_plugin_go.go
  pkg/lint/lintersdb/manager.go
  pkg/lint/lintersdb/manager_test.go
  pkg/lint/lintersdb/validator_test.go
  pkg/lint/package_test.go
  pkg/lint/runner.go
  pkg/printers/printer_test.go
  pkg/printers/tab_test.go
  pkg/printers/text_test.go
  pkg/result/processors/autogenerated_exclude_test.go
  pkg/result/processors/exclude_rules.go
  pkg/result/processors/invalid_issue_test.go
  pkg/result/processors/nolint_test.go
  pkg/result/processors/severity_test.go
  pkg/result/processors/skip_dirs_test.go
  pkg/result/processors/sort_results.go
  pkg/result/processors/sort_results_test.go
  scripts/website/expand_templates/linters.go
  test/enabled_linters_test.go
  test/run_test.go
  test/testshared/analysis_test.go
  test/testshared/directives_test.go
  test/testshared/integration/fix.go
  test/testshared/integration/run.go
  test/testshared/runner_test.go
Labels: linter: update

#4926 dev: fix GO_VERSION in post release workflow
  .github/workflows/post-release.yml
Labels: bug, area: docs, area: ci

#4927 build(deps): bump github.com/securego/gosec/v2 from 5f0084eb01a9 to 81cda2f91fbe
  .golangci.next.reference.yml
  .golangci.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/goanalysis/runners.go
  pkg/golinters/gosec/gosec.go
Labels: dependencies, linter: update version, go

#4929 docs: update GitHub Action assets
  assets/github-action-config.json
Labels: github_actions

#4930 docs: update documentation assets
  .golangci.reference.yml
  CHANGELOG.md
  assets/linters-info.json
  jsonschema/golangci.jsonschema.json
Labels: area: docs, area: JSON schema

#4931 docs: update documentation
  README.md
Labels: area: docs

#4938 feat: check that Go version use to build is greater or equals to the Go version of the project
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/loader.go
Labels: enhancement

#4943 build(deps): bump github.com/securego/gosec/v2 from 81cda2f91fbe to ab3f6c1c83a0
  go.mod
  go.sum
Labels: dependencies, linter: update version, go

#4944 docs: update GitHub Action assets
  CHANGELOG.md
  assets/github-action-config.json
Labels: area: docs

#4945 docs: update documentation
  README.md
Labels: area: docs

#4949 build(deps): bump github.com/quasilyte/go-ruleguard to 0fe6f58b47b1
  go.mod
  go.sum
Labels: dependencies, go

#4960 build(deps): bump github.com/securego/gosec/v2 from ab3f6c1c83a0 to bcec04e78483
  go.mod
  go.sum
Labels: dependencies, linter: update version, go
