Repository golangci/golangci-lint, pull requests merged in 2025-06, with the labels that each got.

#5846 dev: improve comments
  pkg/goanalysis/pkgerrors/parse.go
Labels: topic: cleanup

#5853 dev: display list of staticcheck checks in debug
  pkg/golinters/staticcheck/staticcheck.go
  pkg/logutils/logutils.go
Labels: topic: cosmetic

#5860 feat: deprecate print-resources-usage flag
  pkg/commands/run.go
Labels: topic: cleanup, area: CLI

#5861 docs: add a note about `GL_DEBUG=staticcheck`
  .golangci.next.reference.yml
Labels: area: docs

#5864 fix: deduplicate typecheck errors
  pkg/goanalysis/pkgerrors/errors.go
  pkg/lint/runner.go
Labels: bug, area: output

#5884 fix: typecheck memory leak
  pkg/goanalysis/runner_checker.go
Labels: bug

#5886 docs: update migration guide with --print-issued-lines
  docs/src/docs/product/migration-guide.mdx
Labels: enhancement, area: docs, area: migration

#5885 fix: stop the analysis after the first package analysis error
  pkg/goanalysis/runner.go
  pkg/goanalysis/runner_action.go
  pkg/goanalysis/runner_checker.go
  pkg/goanalysis/runner_loadingpackage.go
Labels: bug, area: core

#5893 fix: formats consistently the code with gci
  pkg/goformatters/gci/gci.go
Labels: bug, linter: update, area: formatters/fmt

#5900 build(deps): bump github.com/bombsimon/wsl/v5 from 4.7.0 to 5.0.0
  .golangci.next.reference.yml
  .golangci.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/commands/internal/migrate/migrate_linters_settings.go
  pkg/commands/internal/migrate/versiontwo/linters_settings.go
  pkg/config/linters_settings.go
  pkg/golinters/wsl/testdata/fix/in/wsl_v4.go
  pkg/golinters/wsl/testdata/fix/in/wsl_v5.go
  pkg/golinters/wsl/testdata/fix/out/wsl_v4.go
  pkg/golinters/wsl/testdata/fix/out/wsl_v5.go
  pkg/golinters/wsl/testdata/ws_v4_cgo.go
  pkg/golinters/wsl/testdata/wsl_v4.go
  pkg/golinters/wsl/testdata/wsl_v4.yml
  pkg/golinters/wsl/testdata/wsl_v5.go
  pkg/golinters/wsl/testdata/wsl_v5_config.go
  pkg/golinters/wsl/testdata/wsl_v5_config.yml
  pkg/golinters/wsl/wsl.go
  pkg/golinters/wsl/wsl_v5.go
  pkg/lint/lintersdb/builder_linter.go
Labels: dependencies, linter: update version, go

#5902 dev: add suggested migration for linter configuration
  .golangci.yml
  pkg/commands/run.go
  pkg/golinters/wsl/wsl.go
  pkg/lint/linter/config.go
  pkg/lint/lintersdb/builder_linter.go
Labels: enhancement, area: migration

#5903 docs: update documentation assets
  .golangci.reference.yml
  assets/cli-help.json
  assets/formatters-info.json
  assets/github-action-config-v1.json
  assets/github-action-config-v2.json
  assets/github-action-config.json
  assets/linters-info.json
  jsonschema/golangci.jsonschema.json
Labels: area: docs, github_actions

#5906 dev: fix GitHub Action assets generation
  assets/github-action-config-v1.json
  assets/github-action-config.json
  scripts/gen_github_action_config/main.go
Labels: bug, area: ci, github_actions
