Repository golangci/golangci-lint, pull requests merged in 2025-05, with the labels that each got.

#5782 build(deps): bump github.com/ashanbrown/makezero from 1.2.0 to 2.0.1
  go.mod
  go.sum
  pkg/golinters/makezero/makezero.go
Labels: dependencies, linter: update version, go

#5783 build(deps): bump github.com/ashanbrown/forbidigo from 1.6.0 to 2.1.0
  go.mod
  go.sum
  pkg/golinters/forbidigo/forbidigo.go
Labels: dependencies, linter: update version, go

#5749 Add swaggo/swag formatter
  .github/dependabot.yml
  .golangci.next.reference.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/config/linters.go
  pkg/goformatters/meta_formatter.go
  pkg/goformatters/swaggo/swaggo.go
  pkg/golinters/swaggo/swaggo.go
  pkg/golinters/swaggo/swaggo_integration_test.go
  pkg/golinters/swaggo/testdata/fix/in/swaggo.go
  pkg/golinters/swaggo/testdata/fix/out/swaggo.go
  pkg/golinters/swaggo/testdata/swaggo.go
  pkg/golinters/swaggo/testdata/swaggo.yml
  pkg/lint/lintersdb/builder_linter.go
  pkg/result/processors/fixer.go
  pkg/result/processors/max_per_file_from_linter.go
Labels: linter: new, area: formatters/fmt

#5718 feat: add arangolint linter
  .github/dependabot.yml
  .golangci.next.reference.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/golinters/arangolint/arangolint.go
  pkg/golinters/arangolint/arangolint_integration_test.go
  pkg/golinters/arangolint/testdata/arangolint.go
  pkg/golinters/arangolint/testdata/arangolint_cgo.go
  pkg/golinters/arangolint/testdata/go.mod
  pkg/golinters/arangolint/testdata/go.sum
  pkg/lint/lintersdb/builder_linter.go
Labels: linter: new

#5761 feat: add embeddedstructfieldcheck linter
  .golangci.next.reference.yml
  go.mod
  go.sum
  jsonschema/golangci.next.jsonschema.json
  pkg/golinters/embeddedstructfieldcheck/embeddedstructfieldcheck.go
  pkg/golinters/embeddedstructfieldcheck/embeddedstructfieldcheck_integration_test.go
  pkg/golinters/embeddedstructfieldcheck/testdata/embeddedstructfieldcheck_comments.go
  pkg/golinters/embeddedstructfieldcheck/testdata/embeddedstructfieldcheck_simple.go
  pkg/golinters/embeddedstructfieldcheck/testdata/embeddedstructfieldcheck_special_cases.go
  pkg/golinters/embeddedstructfieldcheck/testdata/fix/in/comments.go
  pkg/golinters/embeddedstructfieldcheck/testdata/fix/in/simple.go
  pkg/golinters/embeddedstructfieldcheck/testdata/fix/out/comments.go
  pkg/golinters/embeddedstructfieldcheck/testdata/fix/out/simple.go
  pkg/lint/lintersdb/builder_linter.go
Labels: linter: new

#5799 dev: remove AUR publishing
  .goreleaser.yml
Labels: area: install

#5803 dev: restore aur-bin
  .goreleaser.yml
Labels: area: install

#5801 chore: remove dead code
  pkg/golinters/dupl/dupl.go
  pkg/golinters/errcheck/errcheck.go
  pkg/golinters/gochecknoinits/gochecknoinits.go
  pkg/golinters/gocognit/gocognit.go
  pkg/golinters/goconst/goconst.go
  pkg/golinters/gocyclo/gocyclo.go
  pkg/golinters/internal/util.go
  pkg/golinters/prealloc/prealloc.go
Labels: topic: cleanup

#5802 errcheck: add verbose option
  .golangci.next.reference.yml
  jsonschema/golangci.next.jsonschema.json
  pkg/config/linters_settings.go
  pkg/golinters/errcheck/errcheck.go
Labels: enhancement, linter: update

#5804 docs: fix revive defer rule configuration
  .golangci.reference.yml
Labels: bug, area: docs

#5817 dev: consistent version
  cmd/golangci-lint/main.go
Labels: area: CLI

#5821 docs: improve typecheck FAQ
  docs/src/docs/welcome/faq.mdx
Labels: enhancement, area: docs

#5822 docs: note about plugin system
  docs/src/docs/contributing/new-linters.mdx
  docs/src/docs/plugins/go-plugins.mdx
Labels: area: docs, linter: custom

#5827 fix: write the input to stdout when using stdin and there are no changes
  .golangci.next.reference.yml
  pkg/goformat/runner.go
Labels: bug, area: formatters/fmt

#5836 fix: error message when trying to migrate a migrated config
  pkg/commands/migrate.go
Labels: area: CLI, area: migration

#5835 fix: formatters CLI flags help message
  pkg/commands/formatters.go
Labels: area: CLI

#5843 dev: some simplifications
  pkg/commands/internal/migrate/migrate_linter_names.go
  pkg/goformatters/internal/diff.go
  pkg/golinters/govet/govet_test.go
  pkg/golinters/tagliatelle/tagliatelle.go
  pkg/report/log.go
  pkg/result/processors/base_rule.go
  pkg/result/processors/nolint_filter.go
  test/testshared/integration/run.go
  test/testshared/runner.go
Labels: topic: cleanup
